apiVersion: v1
kind: Service
metadata:
  name: smartlist-service
  namespace: smartlist
spec:
  type: LoadBalancer
  selector:
    app: smartlist-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
