/**
 * Seed script: populates productGroups and productVariants collections.
 *
 * Usage:
 *   npx ts-node src/scripts/seed-product-groups.ts
 */
import dotenv from 'dotenv';
dotenv.config({ path: `.env.${process.env.NODE_ENV || 'development'}` });

import mongoose from 'mongoose';
import { connectMongo } from '../infrastructure/db/mongo';
import { normalizeName } from '../utils/normalize';
import { ProductGroupRepository } from '../repositories/product-group.repository';
import { ProductVariantRepository } from '../repositories/product-variant.repository';

// ---------------------------------------------------------------------------
// Seed data
// ---------------------------------------------------------------------------

interface VariantSeed {
  name: string;
  keywords: string[];
  includeKeywords?: string[];
  excludeKeywords?: string[];
}

interface GroupSeed {
  name: string;
  department: string;
  category: string;
  selectionMode: 'canonical' | 'sku';
  keywords: string[];
  includeKeywords: string[];
  excludeKeywords: string[];
  /** 0–100. Higher = shown first in search. Common staples get high priority. */
  priority: number;
  /** Alternative search terms that should match this group */
  aliases: string[];
  variants?: VariantSeed[];
}

const SEED_GROUPS: GroupSeed[] = [
  // ─── חלב ומוצרי חלב ──────────────────────────────────────────────
  {
    name: 'חלב 3%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['חלב', '3%', 'שומן', 'טרי', 'מועשר', 'פרה', 'ליטר', 'בקרטון', 'בקבוק'],
    includeKeywords: ['חלב', '3%'],
    excludeKeywords: [
      '1%', 'ללא לקטוז', 'סויה', 'שקדים', 'קוקוס', 'שוקו',
      'שוקולד', 'ריבת', 'חטיף', 'לוז', 'טעם', 'אבקה', 'חלבון',
      'מעדן', 'משקה', 'אנרגיה', 'פודינג', 'מילקי',
      'דנונה', 'יוגורט', 'קוטג', 'שמנת', 'גבינה', 'עוגה',
      'קפה', 'קקאו', 'וניל', 'תות', 'בננה', 'מוקה',
    ],
    priority: 95,
    aliases: ['חלב', 'חלב רגיל', 'חלב טרי'],
  },
  {
    name: 'חלב 1%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['חלב', '1%', 'דל שומן', 'טרי', 'מועשר', 'פרה', 'ליטר', 'בקרטון', 'בקבוק'],
    includeKeywords: ['חלב', '1%'],
    excludeKeywords: [
      '3%', 'ללא לקטוז', 'סויה', 'שקדים', 'קוקוס', 'שוקו',
      'שוקולד', 'ריבת', 'חטיף', 'לוז', 'טעם', 'אבקה', 'חלבון',
      'מעדן', 'משקה', 'אנרגיה', 'פודינג', 'מילקי',
      'דנונה', 'יוגורט', 'קוטג', 'שמנת', 'גבינה', 'עוגה',
      'קפה', 'קקאו', 'וניל', 'תות', 'בננה', 'מוקה',
    ],
    priority: 70,
    aliases: ['חלב דל שומן'],
  },
  {
    name: "קוטג' 5%",
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['קוטג', '5%', 'גבינה', 'לבנה'],
    includeKeywords: ['קוטג', '5%'],
    excludeKeywords: ['3%', '9%', '12%', 'ללא לקטוז', 'שוקולד', 'פירות', 'ממרח'],
    priority: 75,
    aliases: ['קוטג', 'גבינת קוטג'],
  },
  {
    name: "קוטג' 9%",
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['קוטג', '9%', 'גבינה', 'לבנה'],
    includeKeywords: ['קוטג', '9%'],
    excludeKeywords: ['5%', '12%', 'ללא לקטוז', 'שוקולד', 'פירות', 'ממרח'],
    priority: 70,
    aliases: [],
  },
  {
    name: "קוטג' 12%",
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['קוטג', '12%', 'גבינה', 'לבנה', 'עשיר'],
    includeKeywords: ['קוטג', '12%'],
    excludeKeywords: ['5%', '9%', 'ללא לקטוז', 'שוקולד', 'פירות', 'ממרח'],
    priority: 65,
    aliases: ["קוטג' עשיר"],
  },
  {
    name: 'שמנת מתוקה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['שמנת', 'מתוקה', 'להקצפה'],
    includeKeywords: ['שמנת', 'מתוקה'],
    excludeKeywords: ['חמוצה', 'בישול', 'שוקולד', 'קרם'],
    priority: 55,
    aliases: ['שמנת להקצפה'],
  },
  {
    name: 'שמנת חמוצה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['שמנת', 'חמוצה'],
    includeKeywords: ['שמנת', 'חמוצה'],
    excludeKeywords: ['מתוקה', 'להקצפה'],
    priority: 60,
    aliases: ['שמנת'],
  },
  {
    name: 'יוגורט טבעי',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['יוגורט', 'טבעי', 'לבן'],
    includeKeywords: ['יוגורט'],
    excludeKeywords: ['פירות', 'שתייה', 'דנונה', 'מילקי', 'שוקולד', 'וניל', 'תות', 'בננה', 'מנגו', 'אפרסק', 'סודה', 'עוגה', 'גלידה', 'ממרח', 'רוטב', 'יווני', 'חלבון', 'פרו', 'עיזים'],
    priority: 65,
    aliases: ['יוגורט'],
  },
  {
    name: 'יוגורט יווני',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['יוגורט', 'יווני', 'סמיך', 'שמן'],
    includeKeywords: ['יוגורט', 'יווני'],
    excludeKeywords: ['פירות', 'שתייה', 'שוקולד', 'וניל', 'תות', 'בננה', 'עיזים', 'חלבון', 'פרו'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'יוגורט חלבון',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['יוגורט', 'חלבון', 'פרו', 'עשיר בחלבון'],
    includeKeywords: ['יוגורט', 'חלבון'],
    excludeKeywords: ['פירות', 'שתייה', 'שוקולד', 'וניל', 'תות', 'בננה', 'יווני', 'עיזים'],
    priority: 60,
    aliases: ['יוגורט פרו'],
  },
  {
    name: 'יוגורט עזים',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['יוגורט', 'עיזים', 'עז', 'עזים'],
    includeKeywords: ['יוגורט', 'עיזים'],
    excludeKeywords: ['פירות', 'שתייה', 'שוקולד', 'וניל', 'תות', 'בננה', 'יווני', 'חלבון', 'פרו', 'פרה'],
    priority: 55,
    aliases: ["יוגורט עז"],
  },
  {
    name: 'חמאה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['חמאה', 'תבנית'],
    includeKeywords: ['חמאה'],
    excludeKeywords: ['מרגרינה', 'ממרח', 'בטעם', 'פופקורן', 'פופקו', 'בצק', 'קרקר', 'הוטפופ', 'הוט', 'פופ'],
    priority: 75,
    aliases: [],
  },
  {
    name: 'גבינה צהובה 28%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'צהובה', '28%', 'עמק', 'פרוסות'],
    includeKeywords: ['גבינה', 'צהובה', '28%'],
    excludeKeywords: ['לבנה', 'קוטג', 'שמנת', 'מוצרלה', '9%', '15%', '22%'],
    priority: 80,
    aliases: ['גבינה צהובה', 'גבינה'],
  },
  {
    name: 'גבינה צהובה 9%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'צהובה', '9%', 'עמק', 'פרוסות', 'דלת שומן'],
    includeKeywords: ['גבינה', 'צהובה', '9%'],
    excludeKeywords: ['לבנה', 'קוטג', 'שמנת', 'מוצרלה', '28%', '15%', '22%'],
    priority: 65,
    aliases: ['גבינה צהובה דלת שומן'],
  },
  {
    name: 'גבינה צהובה 15%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'צהובה', '15%', 'עמק', 'פרוסות'],
    includeKeywords: ['גבינה', 'צהובה', '15%'],
    excludeKeywords: ['לבנה', 'קוטג', 'שמנת', 'מוצרלה', '28%', '9%', '22%'],
    priority: 68,
    aliases: [],
  },
  {
    name: 'גבינה צהובה 22%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'צהובה', '22%', 'עמק', 'פרוסות'],
    includeKeywords: ['גבינה', 'צהובה', '22%'],
    excludeKeywords: ['לבנה', 'קוטג', 'שמנת', 'מוצרלה', '28%', '9%', '15%'],
    priority: 72,
    aliases: [],
  },
  {
    name: 'גבינה לבנה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'לבנה', 'שמנת', '5%'],
    includeKeywords: ['גבינה', 'לבנה'],
    excludeKeywords: ['צהובה', 'קוטג', 'מוצרלה', 'בולגרית'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'מוצרלה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['מוצרלה', 'גבינה', 'פיצה'],
    includeKeywords: ['מוצרלה'],
    excludeKeywords: ['צהובה', 'לבנה', 'קוטג'],
    priority: 55,
    aliases: ['גבינה לפיצה'],
  },

  // ─── ביצים ────────────────────────────────────────────────────────
  {
    name: 'ביצים',
    department: 'מזון',
    category: 'ביצים',
    selectionMode: 'sku',
    keywords: ['ביצים', 'ביצה', 'גודל', 'L', 'M', 'תבנית'],
    includeKeywords: ['ביצים'],
    excludeKeywords: ['שוקולד', 'הפתעה', 'אבקה', 'פורס', 'אטריות', 'מצות', 'מקרוני', 'פסטה', 'נודלס', 'מיונז', 'פתיתי'],
    priority: 90,
    aliases: ['ביצה'],
    variants: [
      {
        name: 'תבנית 12',
        keywords: ['12', 'תריסר'],
        includeKeywords: ['12'],
        excludeKeywords: ['30'],
      },
      {
        name: 'תבנית 30',
        keywords: ['30', 'מגש'],
        includeKeywords: ['30'],
        excludeKeywords: ['12'],
      },
    ],
  },

  // ─── לחם ומאפים ───────────────────────────────────────────────────
  {
    name: 'לחם אחיד',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'אחיד', 'פרוס'],
    includeKeywords: ['לחם', 'אחיד'],
    excludeKeywords: ['מלא', 'קמח מלא', 'שיפון', 'כוסמין', 'לבן'],
    priority: 90,
    aliases: ['לחם רגיל', 'לחם פרוס'],
  },
  {
    name: 'לחם לבן',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'לבן', 'פרוס', 'אחיד'],
    includeKeywords: ['לחם', 'לבן'],
    excludeKeywords: ['מלא', 'שיפון', 'כוסמין', 'קמח'],
    priority: 85,
    aliases: ['לחם אחיד'],
  },
  {
    name: 'לחם מלא',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'מלא', 'קמח מלא', 'פרוס'],
    includeKeywords: ['לחם', 'מלא'],
    excludeKeywords: ['אחיד', 'לבן', 'שיפון'],
    priority: 75,
    aliases: ['לחם קמח מלא'],
  },
  {
    name: 'פיתות',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['פיתה', 'פיתות', 'לבנות'],
    includeKeywords: ['פיתות'],
    excludeKeywords: ['טורטיה', 'לאפה', 'אריזה', 'מלא', 'כוסמין'],
    priority: 65,
    aliases: ['פיתה'],
  },
  {
    name: 'פיתות קמח מלא',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['פיתות', 'פיתה', 'קמח מלא', 'מלא', 'חיטה'],
    includeKeywords: ['פיתות', 'מלא'],
    excludeKeywords: ['כוסמין', 'טורטיה', 'לאפה'],
    priority: 55,
    aliases: ['פיתה קמח מלא', 'פיתה מלא', 'פיתות מלאות'],
  },
  {
    name: 'פיתות כוסמין',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['פיתות', 'פיתה', 'כוסמין', 'ספלט'],
    includeKeywords: ['פיתות', 'כוסמין'],
    excludeKeywords: ['מלא', 'טורטיה', 'לאפה'],
    priority: 50,
    aliases: ['פיתה כוסמין'],
  },
  {
    name: 'טורטיה',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['טורטיה', 'טורטיות', 'עטיפה', 'ראפ'],
    includeKeywords: ['טורטיה'],
    excludeKeywords: ['פיתה', 'צ\'יפס', 'נאצ\'וס'],
    priority: 45,
    aliases: ['ראפ'],
  },
  {
    name: 'חלה',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['חלה', 'חלות', 'שבת', 'מתוקה'],
    includeKeywords: ['חלה'],
    excludeKeywords: ['לחם', 'פיתה', 'טורטיה', 'קמח', 'תבנית', 'תבניות', 'אחלה'],
    priority: 60,
    aliases: ['חלות', 'חלת'],
  },
  {
    name: 'לחמניות',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחמניה', 'לחמניות', 'המבורגר', 'כריך'],
    includeKeywords: ['לחמניות'],
    excludeKeywords: ['פיתה', 'באגט', 'תערובת', 'אבקה', 'אבקת'],
    priority: 50,
    aliases: ['לחמניה'],
  },
  {
    name: 'בורקס טרי',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['בורקס', 'בורקסים', 'גבינה', 'תפוחי אדמה', 'בצק עלים', 'מאפה', 'טרי'],
    includeKeywords: ['בורקס'],
    excludeKeywords: ['קפוא', 'פיצה'],
    priority: 55,
    aliases: ['בורקס'],
  },
  {
    name: 'בורקס קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['בורקס', 'בורקסים', 'קפוא', 'קפואים', 'בצק עלים', 'גבינה', 'תפוחי אדמה'],
    includeKeywords: ['בורקס', 'קפוא'],
    excludeKeywords: ['פיצה'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'קרואסון',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['קרואסון', 'קרואסונים', 'שוקולד', 'חמאה'],
    includeKeywords: ['קרואסון'],
    excludeKeywords: ['קפוא'],
    priority: 40,
    aliases: [],
  },

  // ─── בשר ועוף ─────────────────────────────────────────────────────
  {
    name: 'חזה עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['חזה', 'עוף', 'טרי', 'קפוא', 'פרוס'],
    includeKeywords: ['חזה', 'עוף'],
    excludeKeywords: ['טחון', 'שניצל', 'נקניק', 'כרעיים', 'שוקיים', 'כנפיים'],
    priority: 90,
    aliases: ['חזה עוף'],
    variants: [
      {
        name: 'טרי',
        keywords: ['טרי'],
        includeKeywords: ['טרי'],
        excludeKeywords: ['קפוא'],
      },
      {
        name: 'קפוא',
        keywords: ['קפוא'],
        includeKeywords: ['קפוא'],
        excludeKeywords: ['טרי'],
      },
    ],
  },
  {
    name: 'כרעיים עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['כרעיים', 'עוף', 'שוקיים', 'טרי'],
    includeKeywords: ['כרעיים', 'עוף'],
    excludeKeywords: ['חזה', 'כנפיים', 'שניצל', 'קפוא'],
    priority: 55,
    aliases: ['שוקיים עוף'],
  },
  {
    name: 'בשר טחון',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['בשר', 'טחון', 'בקר'],
    includeKeywords: ['בשר', 'טחון'],
    excludeKeywords: ['עוף', 'חזה', 'שניצל', 'נקניק'],
    priority: 70,
    aliases: ['בשר', 'בקר טחון'],
  },
  {
    name: 'שניצל עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['שניצל', 'עוף', 'מטוגן', 'מוכן'],
    includeKeywords: ['שניצל'],
    excludeKeywords: ['חזה', 'כרעיים', 'בקר'],
    priority: 65,
    aliases: ['שניצל'],
  },
  {
    name: 'נקניקיות',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['נקניקיות', 'נקניק', 'נקניקייה', 'הודו', 'עוף'],
    includeKeywords: ['נקניק'],
    excludeKeywords: ['חזה', 'שניצל', 'בשר'],
    priority: 50,
    aliases: ['נקניק'],
  },

  // ─── ירקות ────────────────────────────────────────────────────────
  {
    name: 'עגבניות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['עגבניה', 'עגבניות', 'עגבנייה', 'אדומות', 'טריות'],
    includeKeywords: ['עגבני'],
    excludeKeywords: ['רסק', 'שימורים', 'קטשופ', 'רוטב', 'מיובשות', 'מרק', 'פחית', 'שרי', 'תמר'],
    priority: 80,
    aliases: ['עגבניה'],
  },
  {
    name: 'עגבניות שרי',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['עגבניות', 'שרי', 'אשכולות'],
    includeKeywords: ['שרי'],
    excludeKeywords: ['רסק', 'שימורים', 'קטשופ', 'רוטב', 'מרק', 'פחית'],
    priority: 75,
    aliases: ['עגבניות שרי', 'עגבניית שרי'],
  },
  {
    name: 'עגבניית תמר',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['עגבניות', 'תמר'],
    includeKeywords: ['תמר', 'עגבני'],
    excludeKeywords: ['רסק', 'שימורים', 'קטשופ', 'רוטב', 'מרק', 'פחית'],
    priority: 70,
    aliases: ['עגבניית תמר'],
  },
  {
    name: 'מלפפון',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['מלפפון', 'מלפפונים', 'ירוק'],
    includeKeywords: ['מלפפון', 'מלפפונים'],
    excludeKeywords: ['חמוצים', 'כבוש', 'מלפפונון'],
    priority: 75,
    aliases: [],
  },
  {
    name: 'בצל יבש',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['בצל', 'יבש', 'זהוב'],
    includeKeywords: ['בצל'],
    excludeKeywords: ['ירוק', 'סגול', 'אדום', 'טבעות', 'קפוא', 'מטוגן', 'אבקת', 'מרק'],
    priority: 70,
    aliases: ['בצל', 'בצל לבן'],
  },
  {
    name: 'בצל סגול',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['בצל', 'סגול', 'אדום'],
    includeKeywords: ['בצל', 'סגול'],
    excludeKeywords: ['ירוק', 'טבעות', 'קפוא', 'מטוגן', 'כבוש', 'שימורים'],
    priority: 60,
    aliases: ['בצל אדום'],
  },
  {
    name: 'תפוחי אדמה',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוחי', 'אדמה', 'תפוא'],
    includeKeywords: ['תפוחי אדמה'],
    excludeKeywords: ['פירה', 'צ\'יפס', 'קפוא', 'תפוחים', 'אדום'],
    priority: 80,
    aliases: ['תפוא', 'תפוח אדמה'],
  },
  {
    name: 'תפוח אדמה אדום',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוחי', 'אדמה', 'אדום', 'תפוא'],
    includeKeywords: ['תפוחי אדמה', 'אדום'],
    excludeKeywords: ['פירה', 'צ\'יפס', 'קפוא'],
    priority: 65,
    aliases: ['תפוא אדום'],
  },
  {
    name: 'גזר',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['גזר', 'כתום'],
    includeKeywords: ['גזר'],
    excludeKeywords: ['מיץ', 'קפוא', 'משומר'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'בטטה',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['בטטה', 'בטטות'],
    includeKeywords: ['בטטה'],
    excludeKeywords: ['קפואה', 'מרוסקת', 'מרק'],
    priority: 65,
    aliases: ['בטטה'],
  },
  {
    name: 'שום',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['שום', 'ראש שום'],
    includeKeywords: ['שום'],
    excludeKeywords: ['כבוש', 'בשמן', 'קלוי', 'אבקת', 'ממרח', 'שימורים'],
    priority: 65,
    aliases: ['ראש שום'],
  },
  {
    name: 'קישוא',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['קישוא', 'קישואים'],
    includeKeywords: ['קישוא'],
    excludeKeywords: ['כבוש', 'ממולא', 'קפוא', 'שימורים'],
    priority: 60,
    aliases: ['קישוא'],
  },
  {
    name: 'חציל',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['חציל', 'חצילים'],
    includeKeywords: ['חציל'],
    excludeKeywords: ['כבוש', 'שרוף', 'ממרח', 'קפוא', 'שימורים'],
    priority: 60,
    aliases: ['חציל'],
  },
  {
    name: 'כרוב לבן',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['כרוב', 'לבן'],
    includeKeywords: ['כרוב'],
    excludeKeywords: ['סגול', 'אדום', 'כבוש', 'חמוץ', 'שימורים'],
    priority: 55,
    aliases: ['כרוב'],
  },
  {
    name: 'כרוב אדום',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['כרוב', 'סגול', 'אדום'],
    includeKeywords: ['כרוב', 'סגול'],
    excludeKeywords: ['כבוש', 'חמוץ', 'שימורים'],
    priority: 55,
    aliases: ['כרוב סגול'],
  },
  {
    name: 'כרובית',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['כרובית'],
    includeKeywords: ['כרובית'],
    excludeKeywords: ['קפואה', 'מרוסקת'],
    priority: 60,
    aliases: ['כרובית'],
  },
  {
    name: 'ברוקולי',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['ברוקולי'],
    includeKeywords: ['ברוקולי'],
    excludeKeywords: ['קפוא', 'מרוסק'],
    priority: 60,
    aliases: ['ברוקולי'],
  },
  {
    name: 'פלפל',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['פלפל', 'ירוק', 'אדום', 'צהוב', 'גמבה'],
    includeKeywords: ['פלפל'],
    excludeKeywords: ['שחור', 'טחון', 'תבלין', 'חריף', 'פפריקה', 'כבוש', 'ממולא', 'שימורים', 'רוטב'],
    priority: 65,
    aliases: ['גמבה'],
  },
  {
    name: 'פלפל חריף',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['פלפל', 'חריף', 'צ\'ילי'],
    includeKeywords: ['פלפל', 'חריף'],
    excludeKeywords: ['כבוש', 'שימורים', 'רוטב', 'שחור', 'טחון'],
    priority: 55,
    aliases: ['צ\'ילי'],
  },
  {
    name: 'חסה',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['חסה', 'חסת', 'סלט', 'ירוק'],
    includeKeywords: ['חסה'],
    excludeKeywords: ['רוטב', 'קיסר'],
    priority: 55,
    aliases: ['סלט ירוק'],
  },
  {
    name: 'אבוקדו',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['אבוקדו', 'אבוקאדו'],
    includeKeywords: ['אבוקדו'],
    excludeKeywords: ['גוואקמולי', 'קפוא', 'שמן'],
    priority: 60,
    aliases: ['אבוקאדו'],
  },
  {
    name: 'לימון',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['לימון', 'לימונים'],
    includeKeywords: ['לימון'],
    excludeKeywords: [
      'מיץ', 'משקה', 'ממתק', 'סירופ', 'סודה', 'ספרייט', 'בטעם', 'פרופ', 'מולר',
      'עוגה', 'עוגת', 'פיירי', 'חליטת', 'חליטה', 'פיניש', 'מדיח', 'ניחוח', 'תה',
      'כבוש', 'רוטב', 'קולה', 'אסלה', 'גל', 'מלח', 'סוכריות', 'תבלין',
      'כלים', 'נוזל', 'וופלים', 'סרדינים', 'פלמוליב', 'סנו', 'אקונומיקה', 'סנובון',
      'מנקה', 'ריח', 'פנטסטיק', 'בקרדי', 'בריזר', 'ביסקוויט', 'עוגיות',
      'איולי', 'עללחם', 'טונה', 'עשב', 'שום', 'חומץ', 'ג׳ם', 'ריבה',
    ],
    priority: 55,
    aliases: [],
  },

  // ─── פירות ────────────────────────────────────────────────────────
  {
    name: 'תפוחים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוח', 'תפוחים', 'ירוק', 'אדום'],
    includeKeywords: ['תפוח', 'תפוחים'],
    excludeKeywords: ['מיץ', 'אדמה', 'רסק', 'חומץ', 'מיובש'],
    priority: 70,
    aliases: ['תפוח'],
    variants: [
      {
        name: 'גרני סמית',
        keywords: ['גרני', 'סמית', 'ירוק'],
        includeKeywords: ['גרני', 'סמית'],
        excludeKeywords: ['פינק', 'ליידי'],
      },
      {
        name: 'פינק ליידי',
        keywords: ['פינק', 'ליידי', 'אדום'],
        includeKeywords: ['פינק', 'ליידי'],
        excludeKeywords: ['גרני', 'סמית'],
      },
    ],
  },
  {
    name: 'בננות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['בננה', 'בננות'],
    includeKeywords: ['בננה', 'בננות'],
    excludeKeywords: ['מיובשת', 'צ\'יפס', 'מיץ'],
    priority: 75,
    aliases: ['בננה'],
  },
  {
    name: 'תפוזים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוז', 'תפוזים'],
    includeKeywords: ['תפוז'],
    excludeKeywords: ['מיץ', 'סירופ', 'ממתק'],
    priority: 65,
    aliases: ['תפוז'],
  },
  {
    name: 'קלמנטינות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['קלמנטינה', 'קלמנטינות', 'מנדרינה'],
    includeKeywords: ['קלמנטינ'],
    excludeKeywords: ['מיץ'],
    priority: 50,
    aliases: ['מנדרינה', 'קלמנטינה'],
  },
  {
    name: 'ענבים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['ענבים', 'ענב'],
    includeKeywords: ['ענבים'],
    excludeKeywords: ['יין', 'מיץ', 'צימוקים'],
    priority: 50,
    aliases: ['ענב'],
  },
  {
    name: 'אגסים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['אגס', 'אגסים'],
    includeKeywords: ['אגס'],
    excludeKeywords: ['מיץ', 'ריבה', 'מיובש'],
    priority: 50,
    aliases: ['אגס'],
  },
  {
    name: 'תותים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תות', 'תותים', 'תות שדה'],
    includeKeywords: ['תות'],
    excludeKeywords: ['ריבה', 'מיץ', 'מיובש', 'שוקולד'],
    priority: 55,
    aliases: ['תות', 'תות שדה'],
  },
  {
    name: 'אבטיח',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['אבטיח', 'אבטיחים'],
    includeKeywords: ['אבטיח'],
    excludeKeywords: ['מיץ', 'קפוא'],
    priority: 55,
    aliases: ['אבטיח'],
  },
  {
    name: 'מלון',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['מלון', 'מלונים'],
    includeKeywords: ['מלון'],
    excludeKeywords: ['מיץ', 'קפוא'],
    priority: 50,
    aliases: ['מלון'],
  },
  {
    name: 'מנגו',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['מנגו', 'מנגואים'],
    includeKeywords: ['מנגו'],
    excludeKeywords: ['מיובש', 'מיץ', 'קפוא'],
    priority: 50,
    aliases: ['מנגו'],
  },
  {
    name: 'אננס',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['אננס', 'אננסים'],
    includeKeywords: ['אננס'],
    excludeKeywords: ['שימורים', 'מיץ', 'פחית', 'קפוא'],
    priority: 50,
    aliases: ['אננס'],
  },
  {
    name: 'אפרסקים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['אפרסק', 'אפרסקים'],
    includeKeywords: ['אפרסק'],
    excludeKeywords: ['שימורים', 'ריבה', 'מיץ', 'פחית'],
    priority: 50,
    aliases: ['אפרסק'],
  },
  {
    name: 'נקטרינות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['נקטרינה', 'נקטרינות'],
    includeKeywords: ['נקטרינ'],
    excludeKeywords: ['מיץ', 'קפוא'],
    priority: 45,
    aliases: ['נקטרינה'],
  },
  {
    name: 'קיווי',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['קיווי', 'קיוי'],
    includeKeywords: ['קיווי'],
    excludeKeywords: ['מיץ', 'קפוא'],
    priority: 45,
    aliases: ['קיוי'],
  },

  // ─── דגנים, פסטה וקטניות ──────────────────────────────────────────
  {
    name: 'אורז',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'sku',
    keywords: ['אורז', 'לבן', 'בסמטי'],
    includeKeywords: ['אורז'],
    excludeKeywords: ['עוגיות', 'חטיף', 'פריכיות'],
    priority: 80,
    aliases: [],
    variants: [
      {
        name: 'לבן',
        keywords: ['לבן', 'רגיל'],
        // includeKeywords intentionally empty: the group's 'אורז' is sufficient.
        // 'לבן' scores as a general keyword. Products explicitly named "לבן"
        // rank higher, while jasmine/round/etc. (also white rice) still match.
        includeKeywords: [],
        excludeKeywords: ['בסמטי', 'מלא', 'חום', 'סושי', 'אדום'],
      },
      {
        name: 'בסמטי',
        keywords: ['בסמטי'],
        includeKeywords: ['בסמטי'],
        // 'לבן' removed: "אורז בסמטי לבן" is basmati and should match here.
        excludeKeywords: ['מלא'],
      },
      {
        name: 'מלא',
        keywords: ['מלא', 'חום'],
        includeKeywords: ['מלא'],
        // 'בסמטי' removed: "אורז בסמטי חום מלא" is whole grain and should match.
        excludeKeywords: ['לבן'],
      },
    ],
  },
  {
    name: 'פסטה',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'sku',
    keywords: ['פסטה', 'ספגטי', 'פנה', 'מקרוני'],
    includeKeywords: ['פסטה'],
    excludeKeywords: ['רוטב', 'מוכנה'],
    priority: 75,
    // Multi-word aliases so tokenizer creates AND sets (requires 'פסטה' + shape),
    // preventing single-token 'ספגטי' from matching clothing items.
    aliases: ['פסטה ספגטי', 'פסטה מקרוני', 'פסטה פנה'],
    variants: [
      {
        name: 'ספגטי',
        keywords: ['ספגטי'],
        includeKeywords: ['ספגטי'],
        excludeKeywords: ['פנה', 'מקרוני'],
      },
      {
        name: 'פנה',
        keywords: ['פנה'],
        includeKeywords: ['פנה'],
        excludeKeywords: ['ספגטי', 'מקרוני'],
      },
      {
        name: 'מקרוני',
        keywords: ['מקרוני'],
        includeKeywords: ['מקרוני'],
        excludeKeywords: ['ספגטי', 'פנה'],
      },
    ],
  },
  {
    name: 'קוסקוס',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['קוסקוס', 'פתיתים'],
    includeKeywords: ['קוסקוס'],
    excludeKeywords: ['מוכן', 'סלט'],
    priority: 55,
    aliases: ['פתיתים'],
  },
  {
    name: 'עדשים',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['עדשים', 'אדומות', 'ירוקות'],
    includeKeywords: ['עדשים'],
    excludeKeywords: ['מרק', 'שימורים'],
    priority: 45,
    aliases: [],
  },
  {
    name: 'חומוס (גרגירים)',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['חומוס', 'גרגירי', 'שימורים'],
    includeKeywords: ['חומוס'],
    excludeKeywords: ['ממרח', 'מוכן', 'סלט'],
    priority: 40,
    aliases: ['גרגירי חומוס'],
  },

  // ─── שימורים, ממרחים ורטבים ────────────────────────────────────────
  {
    name: 'טונה בשמן',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טונה', 'שמן', 'צמחי', 'שימורים', 'פחית'],
    includeKeywords: ['טונה'],
    excludeKeywords: ['במים', 'במי', 'זית', 'קנולה', 'סטייק', 'סשימי'],
    priority: 80,
    aliases: ['טונה', 'טונה בשמן'],
  },
  {
    name: 'טונה בשמן זית',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טונה', 'שמן', 'זית', 'כתית', 'שימורים', 'פחית'],
    includeKeywords: ['טונה', 'זית'],
    excludeKeywords: ['קנולה', 'במים', 'במי', 'סטייק', 'סשימי'],
    priority: 75,
    aliases: ['טונה זית'],
  },
  {
    name: 'טונה בשמן קנולה',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טונה', 'שמן', 'קנולה', 'שימורים', 'פחית'],
    includeKeywords: ['טונה', 'קנולה'],
    excludeKeywords: ['זית', 'במים', 'במי', 'סטייק', 'סשימי'],
    priority: 65,
    aliases: ['טונה קנולה'],
  },
  {
    name: 'טונה במים',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טונה', 'מים', 'מי', 'מלח', 'שימורים', 'פחית'],
    includeKeywords: ['טונה'],
    excludeKeywords: ['בשמן', 'שמן', 'סטייק', 'סשימי'],
    priority: 55,
    aliases: ['טונה במי מלח'],
  },
  {
    name: 'תירס מתוק',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['תירס', 'מתוק', 'שימורים', 'פחית'],
    includeKeywords: ['תירס'],
    excludeKeywords: ['קפוא', 'פופקורן', 'טורטיה'],
    priority: 60,
    aliases: ['תירס'],
  },
  {
    name: 'רסק עגבניות',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['רסק', 'עגבניות', 'עגבניה', 'משחה'],
    includeKeywords: ['רסק', 'עגבני'],
    excludeKeywords: ['קטשופ', 'רוטב'],
    priority: 65,
    aliases: ['רסק'],
  },
  {
    name: 'חומוס (ממרח)',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['חומוס', 'ממרח', 'מוכן'],
    includeKeywords: ['חומוס'],
    excludeKeywords: ['גרגירי', 'קטניות', 'יבש'],
    priority: 70,
    aliases: ['חומוס'],
  },
  {
    name: 'טחינה',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טחינה', 'טחינה גולמית', 'שומשום'],
    includeKeywords: ['טחינה'],
    excludeKeywords: ['חלווה', 'ממתק'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'קטשופ',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['קטשופ', 'עגבניות', 'רוטב'],
    includeKeywords: ['קטשופ'],
    excludeKeywords: ['רסק', 'מיונז'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'מיונז',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['מיונז', 'מיונז'],
    includeKeywords: ['מיונז'],
    excludeKeywords: ['קטשופ', 'חרדל'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'רוטב סויה',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['רוטב', 'סויה'],
    includeKeywords: ['סויה', 'רוטב'],
    excludeKeywords: ['שמן', 'חלב', 'אדממה'],
    priority: 35,
    aliases: [],
  },

  // ─── שמנים, תבלינים ומוצרי אפייה ─────────────────────────────────
  {
    name: 'שמן זית',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['שמן', 'זית', 'כתית', 'מעולה'],
    includeKeywords: ['שמן', 'זית'],
    excludeKeywords: ['קנולה', 'חמניות', 'סויה', 'ספריי'],
    priority: 80,
    aliases: ['שמן זית', 'שמן'],
  },
  {
    name: 'שמן קנולה',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['שמן', 'קנולה'],
    includeKeywords: ['שמן', 'קנולה'],
    excludeKeywords: ['זית', 'חמניות'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'שמן סויה',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['שמן', 'סויה', 'בישול'],
    includeKeywords: ['שמן', 'סויה'],
    // 'שמן' (4 chars) matches as substring inside 'בשמן' (Hebrew ב-prefix).
    // Products like "סרדינים בשמן סויה" pass the include check because
    // text.includes('שמן') hits 'בשמן'. Exclude food items where soybean oil
    // is merely an ingredient, not the product itself.
    excludeKeywords: ['רוטב', 'זית', 'קנולה', 'חמניות', 'משקה', 'אדממה', 'טופו',
      'סרדינ', 'טונה', 'דגים', 'שימור', 'פחית', 'כבוש', 'מרינד'],
    priority: 50,
    aliases: ['שמן סויה'],
  },
  {
    name: 'מלח',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['מלח', 'שולחן', 'ים', 'גס', 'דק', 'הימלאיה'],
    includeKeywords: ['מלח'],
    excludeKeywords: ['מלפפון', 'ממרח', 'מרכך', 'שמפו', 'חומוס', 'בייגל', 'מדיח'],
    priority: 60,
    aliases: ['מלח שולחן', 'מלח ים', 'מלח גס', 'מלח דק', 'מלח הימלאיה', 'מלח ים מת'],
  },
  {
    name: 'סוכר לבן',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['סוכר', 'לבן', 'דק', 'גרגירי'],
    includeKeywords: ['סוכר'],
    excludeKeywords: ['סוכריה', 'סוכריות', 'ממתק', 'ממתיק', 'סוכרזית', 'דיאט', 'סטיוויה', 'חום', 'דמרה', 'מוסקובדו', 'וניל', 'אבקת', 'פחות', 'ללא'],
    priority: 70,
    aliases: ['סוכר', 'סוכר לבן', 'סוכר גרגירי'],
  },
  {
    name: 'סוכר חום',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    // 'includeKeywords: [סוכר, חום]' previously required BOTH tokens in the DB
    // AND-query, missing products labeled "סוכר דמרה", "סוכר קנה", "סוכר כהה".
    // Now only 'סוכר' is required; 'חום'/'דמרה'/'כהה' score as general keywords.
    keywords: ['סוכר', 'חום', 'כהה', 'דמרה', 'מוסקובדו', 'קנה'],
    includeKeywords: ['סוכר'],
    excludeKeywords: ['סוכריה', 'סוכריות', 'ממתק', 'ממתיק', 'סוכרזית', 'דיאט', 'לבן', 'גרגירי', 'וניל', 'אבקת', 'פחות', 'ללא'],
    priority: 55,
    aliases: ['סוכר חום', 'סוכר קנה', 'דמרה', 'סוכר כהה'],
  },
  {
    name: 'קמח לבן',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'לבן', 'רגיל', 'רב תכליתי'],
    includeKeywords: ['קמח', 'לבן'],
    excludeKeywords: ['מלא', 'כוסמין', 'שיבולת', 'תירס', 'שיפון', 'שקדים', 'תופח', 'תפוחי', 'מצה', 'מצות', 'אורז', 'גלוטן', 'פסטה', 'נאצ\'וס', 'תכליתי', 'רב תכליתי'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'אבקת אפייה',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['אבקת', 'אפייה'],
    includeKeywords: ['אבקת', 'אפייה'],
    excludeKeywords: ['חלבון', 'שתייה', 'נייר', 'תבנית', 'כביסה'],
    priority: 35,
    aliases: ['אבקת אפיה'],
  },

  // ─── חטיפים, מתוקים ושוקולד ───────────────────────────────────────
  {
    name: 'שוקולד חלב',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['שוקולד', 'חלב', 'טבלה', 'חפיסה', 'אגוזים', 'שקדים', 'קינדר', 'ריטר'],
    includeKeywords: ['שוקולד', 'חלב'],
    excludeKeywords: ['מריר', 'לבן', 'אבקה', 'שתייה', 'גלידה', 'מצה', 'מצות', 'דגני', 'קורנפלקס', 'גרנולה', 'מעדן', 'ציפוי'],
    priority: 65,
    aliases: ['שוקולד'],
  },
  {
    name: 'שוקולד מריר',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['שוקולד', 'מריר', 'טבלה', 'חפיסה', 'קקאו', 'פרמיום'],
    includeKeywords: ['שוקולד', 'מריר'],
    excludeKeywords: ['חלב', 'לבן', 'אבקה', 'שתייה', 'גלידה', 'מצה', 'מצות', 'דגני', 'מעדן', 'ציפוי'],
    priority: 60,
    aliases: ['שוקולד מריר'],
  },
  {
    name: 'שוקולד לבן',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['שוקולד', 'לבן', 'טבלה', 'חפיסה', 'קרמל'],
    includeKeywords: ['שוקולד', 'לבן'],
    excludeKeywords: ['חלב', 'מריר', 'אבקה', 'שתייה', 'גלידה', 'מצה', 'מצות', 'דגני', 'מעדן', 'ציפוי', 'גבינה', 'קוטג'],
    priority: 55,
    aliases: ['שוקולד לבן'],
  },
  {
    name: 'במבה',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['במבה', 'אוסם', 'בוטנים', 'חטיף'],
    includeKeywords: ['במבה'],
    excludeKeywords: [],
    priority: 65,
    aliases: [],
  },
  {
    name: 'ביסלי',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['ביסלי', 'אוסם', 'גריל', 'פיצה', 'חטיף'],
    includeKeywords: ['ביסלי'],
    excludeKeywords: [],
    priority: 65,
    aliases: [],
  },
  {
    name: 'חטיף אנרגיה',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['חטיף', 'אנרגיה', 'גרנולה', 'בר'],
    includeKeywords: ['חטיף'],
    excludeKeywords: ['במבה', 'ביסלי', 'צ\'יפס'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'צ\'יפס',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['צ\'יפס', 'תפוצ\'יפס', 'פרינגלס', 'מלוח'],
    includeKeywords: ['צ\'יפס', 'תפוצ\'יפס'],
    excludeKeywords: ['במבה', 'ביסלי'],
    priority: 55,
    aliases: ['תפוציפס'],
  },
  {
    name: 'עוגיות',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['עוגיות', 'עוגיה', 'ביסקוויט', 'יין', 'שוקולד'],
    includeKeywords: ['עוגיות'],
    excludeKeywords: ['קמח', 'אבקה', 'תבנית', 'עוגה', 'עוגת', 'תערובת'],
    priority: 45,
    aliases: ['ביסקוויט', 'עוגיה'],
  },
  {
    name: 'וופלים',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['וופל', 'וופלים'],
    includeKeywords: ['וופל'],
    excludeKeywords: ['מכונה', 'תבנית'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'עוגה ארוזה',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['עוגה', 'עוגת', 'שיש', 'ארוזה', 'פרוסה', 'אריזה', 'בחושה', 'בראוניז'],
    includeKeywords: ['עוגה'],
    excludeKeywords: ['עוגיות', 'קמח', 'תבנית', 'אבקה', 'תערובת', 'טרי', 'גלידה', 'לעוגה', 'קישוט'],
    priority: 30,
    aliases: ['עוגת', 'עוגות'],
  },
  {
    name: 'פופקורן',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['פופקורן', 'תירס', 'מלוח', 'חמאה'],
    includeKeywords: ['פופקורן'],
    excludeKeywords: ['תירס מתוק'],
    priority: 35,
    aliases: [],
  },

  // ─── דגני בוקר וארוחת בוקר ─────────────────────────────────────────
  {
    name: 'קורנפלקס',
    department: 'מזון',
    category: 'דגני בוקר וארוחת בוקר',
    selectionMode: 'sku',
    keywords: ['קורנפלקס', 'דגני', 'בוקר', 'כוכביות', 'תלמה', 'קלוגס'],
    includeKeywords: ['קורנפלקס'],
    excludeKeywords: ['יוגורט', 'מילקי', 'פודינג', 'לחתול', 'לכלב'],
    priority: 70,
    aliases: ['דגני בוקר', 'כוכביות'],
  },
  {
    name: 'גרנולה',
    department: 'מזון',
    category: 'דגני בוקר וארוחת בוקר',
    selectionMode: 'sku',
    keywords: ['גרנולה', 'שיבולת', 'שועל', 'דגני', 'בוקר'],
    includeKeywords: ['גרנולה'],
    excludeKeywords: ['חטיף'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'שיבולת שועל',
    department: 'מזון',
    category: 'דגני בוקר וארוחת בוקר',
    selectionMode: 'sku',
    keywords: ['שיבולת', 'שועל', 'אוטמיל', 'דייסה', 'דגני', 'בוקר'],
    includeKeywords: ['שיבולת', 'שועל'],
    excludeKeywords: ['גרנולה', 'חטיף', 'עוגיות', 'סנסיטיב'],
    priority: 60,
    aliases: ['אוטמיל', 'דייסה', 'שיבולת שועל'],
  },

  // ─── משקאות ────────────────────────────────────────────────────────
  {
    name: 'מים מינרליים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['מים', 'מינרליים', 'בקבוק'],
    includeKeywords: ['מים', 'מינרליים'],
    excludeKeywords: ['סודה', 'בטעם', 'מוגז'],
    priority: 75,
    aliases: ['מים'],
    variants: [
      {
        name: '1.5 ליטר',
        keywords: ['1.5', 'ליטר'],
        includeKeywords: ['1.5'],
        excludeKeywords: ['6', 'שישיה'],
      },
      {
        name: '6 חבילה',
        keywords: ['6', 'חבילה', 'שישיה'],
        includeKeywords: ['6'],
        excludeKeywords: [],
      },
    ],
  },
  {
    name: 'קולה',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['קולה', 'קוקה', 'פפסי'],
    includeKeywords: ['קולה'],
    excludeKeywords: ['זירו', 'zero', 'דיאט', 'מקס', 'ריקולה', 'רוקולה', 'מולקולה', 'גומי', 'סוכריות', 'חלווה', 'לקריץ', 'פשקז', 'ששון', 'לקקן', 'לוקיטוס'],
    priority: 65,
    aliases: ['קוקה קולה', 'פפסי'],
  },
  {
    name: 'קולה זירו',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['קולה', 'זירו', 'דיאט', 'קוקה', 'פפסי', 'מקס', 'zero'],
    includeKeywords: ['קולה', 'זירו'],
    excludeKeywords: ['ריקולה', 'רוקולה', 'מולקולה', 'גומי', 'סוכריות'],
    priority: 60,
    aliases: ['קולה דיאט', 'קוקה קולה זירו', 'קוקה קולה דיאט', 'פפסי זירו', 'פפסי מקס', 'קולה zero', 'פפסי zero'],
  },
  {
    name: 'מיצים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['מיץ', 'פירות', 'סחוט', 'טבעי', '100%'],
    includeKeywords: ['מיץ'],
    excludeKeywords: ['לתיבול', 'מיונז', 'אבקת', 'ממרח', 'ריבה'],
    priority: 55,
    aliases: ['מיץ', 'מיץ פירות'],
  },
  {
    name: 'מיץ תפוזים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['מיץ', 'תפוזים', 'סחוט', 'טבעי'],
    includeKeywords: ['מיץ', 'תפוז'],
    excludeKeywords: ['ענבים', 'תפוחים', 'גזר'],
    priority: 65,
    aliases: ['מיץ'],
  },
  {
    name: 'סודה / מים מוגזים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['סודה', 'מוגז', 'מים מוגזים', 'מי סודה'],
    includeKeywords: ['סודה'],
    excludeKeywords: ['קולה', 'בטעם', 'לשתיה', 'לשתייה', 'שתיה', 'מכשיר', 'סירופ', 'בלון', 'מתז'],
    priority: 45,
    aliases: ['מי סודה', 'מים מוגזים', 'מים מוגז'],
  },

  // ─── גלידה ────────────────────────────────────────────────────────
  {
    name: 'גלידה',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['גלידה', 'פיינטים', 'משפחתית', 'שטראוס', 'בן אנד ג\'ריס', 'וניל', 'שוקולד', 'קפה'],
    includeKeywords: ['גלידה'],
    excludeKeywords: ['גביע', 'גביעים', 'אחסון', 'מכסים', 'כוס', 'אבקת'],
    priority: 55,
    aliases: ['גלידות'],
  },
  {
    name: 'גביעי גלידה',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['גביע', 'גביעים', 'גלידה', 'וופל', 'מגולגל', 'אמריקאי', 'דרדסים'],
    includeKeywords: ['גביע', 'גלידה'],
    excludeKeywords: ['אחסון', 'מכסים', 'שתייה', 'בולגרית', 'פטה', 'גבינה', 'יין', 'מיץ'],
    priority: 40,
    aliases: ['גביע גלידה', 'קונוס גלידה'],
  },

  // ─── קפואים ───────────────────────────────────────────────────────
  {
    name: 'שעועית ירוקה קפואה',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'canonical',
    keywords: ['שעועית', 'ירוקה', 'קפואה', 'קפוא'],
    includeKeywords: ['שעועית', 'קפוא'],
    excludeKeywords: ['שימורים', 'יבשה'],
    priority: 40,
    aliases: ['שעועית קפואה'],
  },
  {
    name: 'אפונה קפואה',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'canonical',
    keywords: ['אפונה', 'קפואה', 'קפוא'],
    includeKeywords: ['אפונה', 'קפוא'],
    excludeKeywords: ['שימורים', 'יבשה'],
    priority: 40,
    aliases: ['אפונה קפואה'],
  },
  {
    name: 'צ\'יפס קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['צ\'יפס', 'קפוא', 'תפוחי אדמה'],
    includeKeywords: ['צ\'יפס', 'קפוא'],
    excludeKeywords: ['חטיף'],
    priority: 45,
    aliases: [],
  },

  {
    name: 'פילה סלמון קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['פילה', 'סלמון', 'קפוא', 'דג'],
    includeKeywords: ['סלמון', 'קפוא'],
    excludeKeywords: ['טרי', 'מעושן', 'סושי'],
    priority: 55,
    aliases: ['סלמון קפוא'],
  },
  {
    name: 'פילה אמנון קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['פילה', 'אמנון', 'קפוא', 'דג', 'טילאפיה'],
    includeKeywords: ['אמנון', 'קפוא'],
    excludeKeywords: ['טרי', 'סלמון'],
    priority: 45,
    aliases: ['טילאפיה קפוא'],
  },
  {
    name: 'דג מצופה קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['דג', 'מצופה', 'קפוא', 'פירורים', 'שניצל דג'],
    includeKeywords: ['דג', 'קפוא'],
    excludeKeywords: ['פילה', 'סלמון', 'אמנון', 'טרי'],
    priority: 40,
    aliases: ['שניצל דג'],
  },

  // ─── קפה ותה ──────────────────────────────────────────────────────
  {
    name: 'קפה טורקי',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['קפה', 'טורקי', 'עלית', 'נמס'],
    includeKeywords: ['קפה', 'טורקי'],
    excludeKeywords: ['נמס', 'קפסולות', 'אספרסו'],
    priority: 75,
    aliases: ['קפה', 'קפה שחור'],
  },
  {
    name: 'קפה נמס',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['קפה', 'נמס', 'טסטרס', 'נסקפה'],
    includeKeywords: ['קפה', 'נמס'],
    excludeKeywords: ['טורקי', 'קפסולות'],
    priority: 60,
    aliases: ['נסקפה'],
  },
  {
    name: 'קפה קלוי וטחון',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['קפה', 'טחון', 'קלוי', 'פולים', 'פילטר', 'מלבין'],
    includeKeywords: ['קפה', 'טחון'],
    excludeKeywords: ['נמס', 'קפסולות', 'טורקי', 'אייס', 'מכונת', 'מסיר', 'כוסות', 'מטחנת', 'אבקה'],
    priority: 55,
    aliases: ['פולי קפה', 'קפה גרגירים', 'קפה לפילטר', 'קפה מגורען', 'קפה פולים'],
  },
  {
    name: 'תה',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['תה', 'שקיקים', 'נענע', 'ירוק', 'שחור'],
    includeKeywords: ['תה'],
    excludeKeywords: ['קפה'],
    priority: 60,
    aliases: [],
  },

  // ─── אגוזים וגרעינים ────────────────────────────────────────────────
  {
    name: 'קשיו',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['קשיו', 'קשיוז', 'אגוזי קשיו', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['קשיו'],
    excludeKeywords: ['חמאה', 'ממרח', 'תפזורת', 'משקל'],
    priority: 45,
    aliases: [],
  },
  {
    name: 'שקדים',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['שקדים', 'שקד', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['שקדים'],
    excludeKeywords: ['חלב', 'משקה', 'חמאה', 'ממרח', 'תפזורת', 'משקל'],
    priority: 45,
    aliases: [],
  },
  {
    name: 'אגוזי מלך',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['אגוזי מלך', 'אגוז מלך', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['אגוז', 'מלך'],
    excludeKeywords: ['חמאה', 'ממרח', 'תפזורת', 'משקל'],
    priority: 40,
    aliases: [],
  },
  {
    name: 'גרעיני חמניה',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['גרעיני חמניה', 'גרעינים', 'חמניות', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['גרעינ', 'חמני'],
    excludeKeywords: ['שמן', 'תפזורת', 'משקל'],
    priority: 40,
    aliases: ['גרעינים'],
  },
  {
    name: 'פיסטוק',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['פיסטוק', 'פיסטוקים', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['פיסטוק'],
    excludeKeywords: ['גלידה', 'תפזורת', 'משקל'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'בוטנים',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['בוטנים', 'בוטן', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['בוטנים'],
    excludeKeywords: ['חמאה', 'ממרח', 'במבה', 'תפזורת', 'משקל'],
    priority: 40,
    aliases: [],
  },
  {
    name: 'פיצוחים תפזורת',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'canonical',
    keywords: ['פיצוחים', 'אגוזים', 'גרעינים', 'שקדים', 'קשיו', 'בוטנים', 'פיסטוק', 'אגוזי מלך', 'תפזורת', 'משקל'],
    includeKeywords: ['פיצוחים', 'תפזורת', 'אגוז', 'גרעינ', 'משקל'],
    excludeKeywords: ['ארוז', 'שקית', 'חמאה', 'ממרח'],
    priority: 25,
    aliases: [],
  },

  // ─── ניקיון ובית ──────────────────────────────────────────────────
  {
    name: 'נייר טואלט',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['נייר', 'טואלט', 'גלילים'],
    includeKeywords: ['נייר', 'טואלט'],
    excludeKeywords: ['מגבת', 'סופג'],
    priority: 70,
    aliases: ['נייר טואלט'],
  },
  {
    name: 'טישו / ממחטות',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['טישו', 'ממחטות', 'קלינקס', 'נייר פנים', 'נייר אף'],
    includeKeywords: ['טישו'],
    // ארטישוק and פטישון both contain טישו as a substring — must exclude explicitly
    excludeKeywords: ['ארטישוק', 'פטישון'],
    priority: 55,
    aliases: ['ממחטות', 'נייר טישו'],
  },
  {
    name: 'סבון כלים',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['סבון', 'כלים', 'נוזלי'],
    includeKeywords: ['סבון', 'כלים'],
    excludeKeywords: ['גוף', 'ידיים', 'כביסה'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'אקונומיקה',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'canonical',
    keywords: ['אקונומיקה', 'לבן', 'חומר חיטוי'],
    includeKeywords: ['אקונומיקה'],
    excludeKeywords: [],
    priority: 45,
    aliases: [],
  },
  {
    name: 'אבקת כביסה',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['אבקת', 'כביסה', 'אריאל', 'פרסיל', 'טייד', 'מקסימה', 'קולון', 'ביומט', 'טופ', 'אקטיב'],
    includeKeywords: ['אבקת', 'כביסה'],
    excludeKeywords: ['גל', 'נוזל', 'קפסול', 'מרכך', 'וניש', 'שמפו'],
    priority: 60,
    aliases: ['אבקת כביסה'],
  },
  {
    name: 'סבון ידיים',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['סבון', 'ידיים', 'נוזלי', 'פלמוליב', 'קמיל', 'פינוק', 'קצף'],
    includeKeywords: ['ידיים'],
    excludeKeywords: ['כביסה', 'כלים', 'גוף', 'שמפו', 'קרם'],
    priority: 55,
    aliases: ['סבון ידיים', 'סבון נוזלי לידיים'],
  },
  {
    name: 'מגבונים לתינוק',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['מגבונים', 'לחים', 'בייבי', 'תינוק', 'האגיס', 'בייביסיטר'],
    includeKeywords: ['מגבונ'],
    excludeKeywords: ['ניקוי', 'ניקיון', 'רצפה', 'משטח', 'חומץ', 'איפור', 'עיניים', 'אינטימ', 'מחטא', 'כביסכל', 'כביסה', 'טואלט', 'דיזטול'],
    priority: 55,
    aliases: ['מגבוני תינוק', 'מגבונים בייבי', 'מגבונים לחים', 'מגבונים'],
  },
  {
    name: 'מגבוני ניקוי',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'canonical',
    keywords: ['מגבונים', 'ניקוי', 'ניקיון', 'משטח', 'רצפה', 'כביסכל', 'כללי', 'דלי'],
    includeKeywords: ['מגבונ', 'ניקוי'],
    excludeKeywords: ['בייבי', 'תינוק', 'איפור', 'עיניים', 'אינטימ', 'טואלט', 'האגיס', 'בייביסיטר', 'משקפי', 'פנים', 'עפעפ'],
    priority: 45,
    aliases: ['מגבוני ניקיון', 'מגבוני רצפה', 'מגבוני משטחים'],
  },
  // ─── משקאות צמחיים ──────────────────────────────────────────────
  {
    name: 'משקה שיבולת שועל',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['משקה', 'שיבולת', 'שועל', 'אוטלי', 'צמחי'],
    includeKeywords: ['שיבולת', 'שועל'],
    excludeKeywords: ['דייסה', 'גרנולה', 'חטיף', 'עוגיות'],
    priority: 55,
    aliases: ['חלב שיבולת שועל'],
  },
  {
    name: 'משקה שקדים',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['משקה', 'שקדים', 'שקד', 'צמחי', 'אלפרו'],
    includeKeywords: ['שקד'],
    excludeKeywords: ['פיצוחים', 'ארוז', 'שקית', 'גלידה', 'חטיף'],
    priority: 55,
    aliases: ['חלב שקדים'],
  },
  {
    name: 'משקה סויה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['משקה', 'סויה', 'סוי', 'צמחי', 'אלפרו'],
    includeKeywords: ['סויה'],
    excludeKeywords: ['רוטב', 'אדממה', 'טופו', 'שעועית'],
    priority: 55,
    aliases: ['חלב סויה'],
  },
  // ─── גבינות נוספות ──────────────────────────────────────────────
  {
    name: 'גבינה בולגרית',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'בולגרית', 'מלוחה'],
    includeKeywords: ['בולגרית'],
    excludeKeywords: [],
    priority: 60,
    aliases: [],
  },
  {
    name: 'גבינת עיזים',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'עיזים', 'עז'],
    includeKeywords: ['עיזים'],
    excludeKeywords: ['יוגורט', 'חלב'],
    priority: 55,
    aliases: ['גבינה עז'],
  },
  {
    name: 'פרמזן',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['פרמזן', 'פרמג\'נו', 'גבינה', 'איטלקית', 'מגורדת'],
    includeKeywords: ['פרמזן'],
    excludeKeywords: [],
    priority: 55,
    aliases: ['פרמג\'נו'],
  },
  {
    name: 'ריקוטה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['ריקוטה', 'גבינה', 'איטלקית'],
    includeKeywords: ['ריקוטה'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
  // ─── עוף ───────────────────────────────────────────────────────
  {
    name: 'עוף שלם',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['עוף', 'שלם', 'פרגית', 'קפוא', 'טרי'],
    includeKeywords: ['עוף', 'שלם'],
    excludeKeywords: ['חזה', 'כנף', 'כרע', 'שוק', 'שניצל', 'נקניק'],
    priority: 60,
    aliases: ['פרגית'],
  },
  {
    name: 'כנפיים עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['כנפיים', 'כנף', 'עוף', 'טרי'],
    includeKeywords: ['כנפיי'],
    excludeKeywords: ['שניצל', 'נקניק'],
    priority: 55,
    aliases: ['כנף עוף'],
  },
  // ─── דגים ──────────────────────────────────────────────────────
  {
    name: 'דג טרי',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['דג', 'דגים', 'טרי', 'פילה'],
    includeKeywords: ['דג'],
    excludeKeywords: ['קפוא', 'שימורים', 'פחית', 'מצופה', 'מעושן', 'מלוח', 'דגני'],
    priority: 75,
    aliases: ['דגים'],
  },
  {
    name: 'סלמון טרי',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['סלמון', 'טרי', 'פילה', 'נורבגי'],
    includeKeywords: ['סלמון'],
    excludeKeywords: ['קפוא', 'מעושן', 'מלוח', 'שימורים'],
    priority: 60,
    aliases: [],
  },
  {
    name: 'דניס',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['דניס', 'דג', 'טרי'],
    includeKeywords: ['דניס'],
    excludeKeywords: ['קפוא'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'ברמונדי',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['ברמונדי', 'דג', 'טרי', 'פילה'],
    includeKeywords: ['ברמונדי'],
    excludeKeywords: ['קפוא'],
    priority: 55,
    aliases: [],
  },
  // ─── לחם ומאפים נוספים ─────────────────────────────────────────
  {
    name: 'באגט',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['באגט', 'בגט', 'צרפתי'],
    includeKeywords: ['באגט'],
    excludeKeywords: ['תערובת', 'אבקה', 'ממרח', 'רוטב', 'קמח'],
    priority: 50,
    aliases: ['בגט', 'לחם צרפתי'],
  },
  {
    name: 'לחם שיפון',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'שיפון', 'כהה'],
    includeKeywords: ['לחם', 'שיפון'],
    excludeKeywords: ['מצות', 'מצה'],
    priority: 50,
    aliases: [],
  },
  {
    name: 'מצות',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['מצות', 'מצה', 'פסח', 'שיפון', 'מלא', 'כוסמין'],
    includeKeywords: ['מצות'],
    excludeKeywords: ['קמח', 'אבקה'],
    priority: 55,
    aliases: ['מצה', 'מצות שיפון', 'מצות מלא'],
  },
  // ─── פסטה / אטריות ────────────────────────────────────────────
  {
    name: 'אטריות',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'sku',
    keywords: ['אטריות', 'אטריה', 'נודלס', 'רחבות', 'ביצים'],
    includeKeywords: ['אטריו'],
    excludeKeywords: ['אורז'],
    priority: 50,
    aliases: ['נודלס'],
  },
  // ─── קמח ──────────────────────────────────────────────────────
  {
    name: 'קמח מלא',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'מלא', 'חיטה'],
    includeKeywords: ['קמח', 'מלא'],
    excludeKeywords: [],
    priority: 76,
    aliases: ['קמח חיטה מלא'],
  },
  {
    name: 'קמח כוסמין',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'כוסמין', 'ספלט'],
    includeKeywords: ['קמח', 'כוסמין'],
    excludeKeywords: [],
    priority: 50,
    aliases: ['קמח ספלט'],
  },
  {
    name: 'קמח שיפון',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'שיפון'],
    includeKeywords: ['קמח', 'שיפון'],
    excludeKeywords: ['לחם'],
    priority: 50,
    aliases: [],
  },
  {
    name: 'קמח שקדים',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'שקדים'],
    includeKeywords: ['קמח', 'שקדים'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
  {
    name: 'קמח תופח',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'תופח'],
    includeKeywords: ['קמח', 'תופח'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  await connectMongo();

  const groupRepo = new ProductGroupRepository();
  const variantRepo = new ProductVariantRepository();

  let groupCount = 0;
  let variantCount = 0;

  for (const seed of SEED_GROUPS) {
    const normalizedName = normalizeName(seed.name);
    const normalizedKeywords = seed.keywords.map(normalizeName).filter(Boolean);

    const group = await groupRepo.upsertByName({
      name: seed.name,
      normalizedName,
      department: seed.department,
      category: seed.category,
      selectionMode: seed.selectionMode,
      keywords: seed.keywords,
      normalizedKeywords,
      includeKeywords: seed.includeKeywords,
      excludeKeywords: seed.excludeKeywords,
      priority: seed.priority,
      aliases: seed.aliases,
    });
    groupCount++;

    if (seed.variants) {
      for (const v of seed.variants) {
        const normalizedVarKeywords = v.keywords.map(normalizeName).filter(Boolean);

        await variantRepo.upsertByGroupAndName({
          groupId: group.id,
          name: v.name,
          keywords: v.keywords,
          normalizedKeywords: normalizedVarKeywords,
          includeKeywords: v.includeKeywords ?? [],
          excludeKeywords: v.excludeKeywords ?? [],
        });
        variantCount++;
      }
    }
  }

  // Clean up stale groups that no longer exist in the seed
  const seededNames = new Set(SEED_GROUPS.map((s) => normalizeName(s.name)));
  const ProductGroupModel = mongoose.connection.collection('productgroups');
  const allDocs = await ProductGroupModel.find({}, { projection: { normalizedName: 1 } }).toArray();
  const staleIds = allDocs
    .filter((d) => !seededNames.has(d.normalizedName))
    .map((d) => d._id);
  if (staleIds.length > 0) {
    await ProductGroupModel.deleteMany({ _id: { $in: staleIds } });
    console.log(`Removed ${staleIds.length} stale product groups.`);
  }

  console.log(`Seeded ${groupCount} product groups and ${variantCount} variants.`);

  await mongoose.disconnect();
  process.exit(0);
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
