/**
 * Seed script: populates productGroups and productVariants collections.
 *
 * Usage:
 *   npx ts-node src/scripts/seed-product-groups.ts
 */
import dotenv from 'dotenv';
dotenv.config({ path: `.env.${process.env.NODE_ENV || 'development'}` });

import mongoose from 'mongoose';
import { connectMongo } from '../infrastructure/db/mongo';
import { normalizeName } from '../utils/normalize';
import { ProductGroupRepository } from '../repositories/product-group.repository';
import { ProductVariantRepository } from '../repositories/product-variant.repository';

// ---------------------------------------------------------------------------
// Seed data
// ---------------------------------------------------------------------------

interface VariantSeed {
  name: string;
  keywords: string[];
  includeKeywords?: string[];
  excludeKeywords?: string[];
}

interface GroupSeed {
  name: string;
  department: string;
  category: string;
  selectionMode: 'canonical' | 'sku';
  keywords: string[];
  includeKeywords: string[];
  excludeKeywords: string[];
  /** 0–100. Higher = shown first in search. Common staples get high priority. */
  priority: number;
  /** Alternative search terms that should match this group */
  aliases: string[];
  variants?: VariantSeed[];
}

const SEED_GROUPS: GroupSeed[] = [
  // ─── חלב ומוצרי חלב ──────────────────────────────────────────────
  {
    name: 'חלב 3%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['חלב', '3%', 'שומן', 'טרי', 'מועשר', 'פרה', 'ליטר', 'בקרטון', 'בקבוק'],
    includeKeywords: ['חלב', '3%'],
    excludeKeywords: [
      '1%', 'ללא לקטוז', 'סויה', 'שקדים', 'קוקוס', 'שוקו',
      'שוקולד', 'ריבת', 'חטיף', 'לוז', 'טעם', 'אבקה', 'חלבון',
      'מעדן', 'משקה', 'אנרגיה', 'פודינג', 'מילקי',
      'דנונה', 'יוגורט', 'קוטג', 'שמנת', 'גבינה', 'עוגה',
      'קפה', 'קקאו', 'וניל', 'תות', 'בננה', 'מוקה',
    ],
    priority: 95,
    aliases: ['חלב', 'חלב רגיל', 'חלב טרי'],
  },
  {
    name: 'חלב 1%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['חלב', '1%', 'דל שומן', 'טרי', 'מועשר', 'פרה', 'ליטר', 'בקרטון', 'בקבוק'],
    includeKeywords: ['חלב', '1%'],
    excludeKeywords: [
      '3%', 'ללא לקטוז', 'סויה', 'שקדים', 'קוקוס', 'שוקו',
      'שוקולד', 'ריבת', 'חטיף', 'לוז', 'טעם', 'אבקה', 'חלבון',
      'מעדן', 'משקה', 'אנרגיה', 'פודינג', 'מילקי',
      'דנונה', 'יוגורט', 'קוטג', 'שמנת', 'גבינה', 'עוגה',
      'קפה', 'קקאו', 'וניל', 'תות', 'בננה', 'מוקה',
    ],
    priority: 70,
    aliases: ['חלב דל שומן'],
  },
  {
    name: "קוטג' 5%",
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['קוטג', '5%', 'גבינה', 'לבנה'],
    includeKeywords: ['קוטג', '5%'],
    excludeKeywords: ['3%', '9%', 'ללא לקטוז', 'שוקולד', 'פירות', 'ממרח'],
    priority: 75,
    aliases: ['קוטג', 'גבינת קוטג'],
  },
  {
    name: 'שמנת מתוקה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['שמנת', 'מתוקה', 'להקצפה'],
    includeKeywords: ['שמנת', 'מתוקה'],
    excludeKeywords: ['חמוצה', 'בישול', 'שוקולד', 'קרם'],
    priority: 55,
    aliases: ['שמנת להקצפה'],
  },
  {
    name: 'שמנת חמוצה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['שמנת', 'חמוצה'],
    includeKeywords: ['שמנת', 'חמוצה'],
    excludeKeywords: ['מתוקה', 'להקצפה'],
    priority: 60,
    aliases: ['שמנת'],
  },
  {
    name: 'יוגורט טבעי',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['יוגורט', 'טבעי', 'לבן'],
    includeKeywords: ['יוגורט'],
    excludeKeywords: ['פירות', 'שתייה', 'דנונה', 'מילקי', 'שוקולד', 'וניל', 'תות', 'בננה', 'מנגו', 'אפרסק', 'סודה', 'עוגה', 'גלידה', 'ממרח', 'רוטב'],
    priority: 65,
    aliases: ['יוגורט'],
  },
  {
    name: 'חמאה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['חמאה', 'תבנית'],
    includeKeywords: ['חמאה'],
    excludeKeywords: ['מרגרינה', 'ממרח', 'בטעם', 'פופקורן', 'פופקו', 'בצק', 'קרקר', 'הוטפופ', 'הוט', 'פופ'],
    priority: 75,
    aliases: [],
  },
  {
    name: 'גבינה צהובה 28%',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'צהובה', '28%', 'עמק', 'פרוסות'],
    includeKeywords: ['גבינה', 'צהובה'],
    excludeKeywords: ['לבנה', 'קוטג', 'שמנת', 'מוצרלה'],
    priority: 80,
    aliases: ['גבינה צהובה', 'גבינה'],
  },
  {
    name: 'גבינה לבנה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'לבנה', 'שמנת', '5%'],
    includeKeywords: ['גבינה', 'לבנה'],
    excludeKeywords: ['צהובה', 'קוטג', 'מוצרלה', 'בולגרית'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'מוצרלה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['מוצרלה', 'גבינה', 'פיצה'],
    includeKeywords: ['מוצרלה'],
    excludeKeywords: ['צהובה', 'לבנה', 'קוטג'],
    priority: 55,
    aliases: ['גבינה לפיצה'],
  },

  // ─── ביצים ────────────────────────────────────────────────────────
  {
    name: 'ביצים',
    department: 'מזון',
    category: 'ביצים',
    selectionMode: 'sku',
    keywords: ['ביצים', 'ביצה', 'גודל', 'L', 'M', 'תבנית'],
    includeKeywords: ['ביצים'],
    excludeKeywords: ['שוקולד', 'הפתעה', 'אבקה', 'פורס', 'אטריות', 'מצות', 'מקרוני', 'פסטה', 'נודלס', 'מיונז', 'פתיתי'],
    priority: 90,
    aliases: ['ביצה'],
    variants: [
      {
        name: 'תבנית 12',
        keywords: ['12', 'תריסר'],
        includeKeywords: ['12'],
        excludeKeywords: ['30'],
      },
      {
        name: 'תבנית 30',
        keywords: ['30', 'מגש'],
        includeKeywords: ['30'],
        excludeKeywords: ['12'],
      },
    ],
  },

  // ─── לחם ומאפים ───────────────────────────────────────────────────
  {
    name: 'לחם אחיד',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'אחיד', 'פרוס', 'לבן'],
    includeKeywords: ['לחם', 'אחיד'],
    excludeKeywords: ['מלא', 'קמח מלא', 'שיפון', 'כוסמין'],
    priority: 90,
    aliases: ['לחם', 'לחם לבן', 'לחם רגיל', 'לחם פרוס'],
  },
  {
    name: 'לחם מלא',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'מלא', 'קמח מלא', 'פרוס'],
    includeKeywords: ['לחם', 'מלא'],
    excludeKeywords: ['אחיד', 'לבן', 'שיפון'],
    priority: 75,
    aliases: ['לחם קמח מלא'],
  },
  {
    name: 'פיתות',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['פיתה', 'פיתות', 'לבנות'],
    includeKeywords: ['פיתה', 'פיתות'],
    excludeKeywords: ['טורטיה', 'לאפה'],
    priority: 65,
    aliases: ['פיתה'],
  },
  {
    name: 'טורטיה',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['טורטיה', 'טורטיות', 'עטיפה', 'ראפ'],
    includeKeywords: ['טורטיה'],
    excludeKeywords: ['פיתה', 'צ\'יפס', 'נאצ\'וס'],
    priority: 45,
    aliases: ['ראפ'],
  },
  {
    name: 'חלה',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['חלה', 'חלות', 'שבת', 'מתוקה'],
    includeKeywords: ['חלה'],
    excludeKeywords: ['לחם', 'פיתה', 'טורטיה'],
    priority: 60,
    aliases: ['חלות'],
  },
  {
    name: 'לחמניות',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['לחמניה', 'לחמניות', 'המבורגר', 'כריך'],
    includeKeywords: ['לחמני'],
    excludeKeywords: ['לחם', 'פיתה', 'באגט', 'תערובת', 'אבקה'],
    priority: 50,
    aliases: ['לחמניה'],
  },
  {
    name: 'בורקס טרי',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['בורקס', 'בורקסים', 'גבינה', 'תפוחי אדמה', 'בצק עלים', 'מאפה', 'טרי'],
    includeKeywords: ['בורקס'],
    excludeKeywords: ['קפוא', 'פיצה'],
    priority: 55,
    aliases: ['בורקס'],
  },
  {
    name: 'בורקס קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['בורקס', 'בורקסים', 'קפוא', 'קפואים', 'בצק עלים', 'גבינה', 'תפוחי אדמה'],
    includeKeywords: ['בורקס', 'קפוא'],
    excludeKeywords: ['פיצה'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'קרואסון',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['קרואסון', 'קרואסונים', 'שוקולד', 'חמאה'],
    includeKeywords: ['קרואסון'],
    excludeKeywords: ['קפוא'],
    priority: 40,
    aliases: [],
  },

  // ─── בשר ועוף ─────────────────────────────────────────────────────
  {
    name: 'חזה עוף טרי',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['חזה', 'עוף', 'טרי', 'פילה'],
    includeKeywords: ['חזה', 'עוף'],
    excludeKeywords: ['קפוא', 'טחון', 'שניצל', 'נקניק', 'כרעיים', 'שוקיים', 'כנפיים'],
    priority: 90,
    aliases: ['עוף', 'חזה עוף', 'פילה עוף', 'עוף טרי'],
    variants: [
      {
        name: 'רגיל',
        keywords: ['רגיל'],
        includeKeywords: [],
        excludeKeywords: ['אורגני'],
      },
      {
        name: 'ארוז מראש',
        keywords: ['ארוז', 'אטום'],
        includeKeywords: ['ארוז'],
        excludeKeywords: [],
      },
    ],
  },
  {
    name: 'כרעיים עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['כרעיים', 'עוף', 'שוקיים', 'טרי'],
    includeKeywords: ['כרעיים', 'עוף'],
    excludeKeywords: ['חזה', 'כנפיים', 'שניצל', 'קפוא'],
    priority: 55,
    aliases: ['שוקיים עוף'],
  },
  {
    name: 'בשר טחון',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['בשר', 'טחון', 'בקר'],
    includeKeywords: ['בשר', 'טחון'],
    excludeKeywords: ['עוף', 'חזה', 'שניצל', 'נקניק'],
    priority: 70,
    aliases: ['בשר', 'בקר טחון'],
  },
  {
    name: 'שניצל עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['שניצל', 'עוף', 'מטוגן', 'מוכן'],
    includeKeywords: ['שניצל'],
    excludeKeywords: ['חזה', 'כרעיים', 'בקר'],
    priority: 65,
    aliases: ['שניצל'],
  },
  {
    name: 'נקניקיות',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['נקניקיות', 'נקניק', 'נקניקייה', 'הודו', 'עוף'],
    includeKeywords: ['נקניק'],
    excludeKeywords: ['חזה', 'שניצל', 'בשר'],
    priority: 50,
    aliases: ['נקניק'],
  },

  // ─── ירקות ────────────────────────────────────────────────────────
  {
    name: 'עגבניות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['עגבניה', 'עגבניות', 'עגבנייה', 'אדומות', 'שרי', 'טריות'],
    includeKeywords: ['עגבני'],
    excludeKeywords: ['רסק', 'שימורים', 'קטשופ', 'רוטב', 'מיובשות', 'מרק', 'פחית'],
    priority: 80,
    aliases: ['עגבניה'],
  },
  {
    name: 'מלפפון',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['מלפפון', 'מלפפונים', 'ירוק'],
    includeKeywords: ['מלפפון', 'מלפפונים'],
    excludeKeywords: ['חמוצים', 'כבוש', 'מלפפונון'],
    priority: 75,
    aliases: [],
  },
  {
    name: 'בצל יבש',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['בצל', 'יבש', 'זהוב'],
    includeKeywords: ['בצל'],
    excludeKeywords: ['ירוק', 'סגול', 'אדום', 'טבעות', 'קפוא'],
    priority: 70,
    aliases: ['בצל'],
  },
  {
    name: 'תפוחי אדמה',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוחי', 'אדמה', 'תפוא'],
    includeKeywords: ['תפוחי אדמה'],
    excludeKeywords: ['פירה', 'צ\'יפס', 'קפוא', 'תפוחים'],
    priority: 80,
    aliases: ['תפוא', 'תפוח אדמה'],
  },
  {
    name: 'גזר',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['גזר', 'כתום'],
    includeKeywords: ['גזר'],
    excludeKeywords: ['מיץ', 'קפוא', 'משומר'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'פלפל',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['פלפל', 'ירוק', 'אדום', 'צהוב'],
    includeKeywords: ['פלפל'],
    excludeKeywords: ['שחור', 'טחון', 'תבלין', 'חריף', 'פפריקה'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'חסה',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['חסה', 'חסת', 'סלט', 'ירוק'],
    includeKeywords: ['חסה'],
    excludeKeywords: ['רוטב', 'קיסר'],
    priority: 55,
    aliases: ['סלט ירוק'],
  },
  {
    name: 'אבוקדו',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['אבוקדו', 'אבוקאדו'],
    includeKeywords: ['אבוקדו'],
    excludeKeywords: ['גוואקמולי', 'קפוא', 'שמן'],
    priority: 60,
    aliases: ['אבוקאדו'],
  },
  {
    name: 'לימון',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['לימון', 'לימונים'],
    includeKeywords: ['לימון'],
    excludeKeywords: [
      'מיץ', 'משקה', 'ממתק', 'סירופ', 'סודה', 'ספרייט', 'בטעם', 'פרופ', 'מולר',
      'עוגה', 'עוגת', 'פיירי', 'חליטת', 'חליטה', 'פיניש', 'מדיח', 'ניחוח', 'תה',
      'כבוש', 'רוטב', 'קולה', 'אסלה', 'גל', 'מלח', 'סוכריות', 'תבלין',
      'כלים', 'נוזל', 'וופלים', 'סרדינים', 'פלמוליב', 'סנו', 'אקונומיקה', 'סנובון',
      'מנקה', 'ריח', 'פנטסטיק', 'בקרדי', 'בריזר', 'ביסקוויט', 'עוגיות',
      'איולי', 'עללחם', 'טונה', 'עשב', 'שום', 'חומץ', 'ג׳ם', 'ריבה',
    ],
    priority: 55,
    aliases: [],
  },

  // ─── פירות ────────────────────────────────────────────────────────
  {
    name: 'תפוחים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוח', 'תפוחים', 'ירוק', 'אדום'],
    includeKeywords: ['תפוח', 'תפוחים'],
    excludeKeywords: ['מיץ', 'אדמה', 'רסק', 'חומץ', 'מיובש'],
    priority: 70,
    aliases: ['תפוח'],
    variants: [
      {
        name: 'גרני סמית',
        keywords: ['גרני', 'סמית', 'ירוק'],
        includeKeywords: ['גרני', 'סמית'],
        excludeKeywords: ['פינק', 'ליידי'],
      },
      {
        name: 'פינק ליידי',
        keywords: ['פינק', 'ליידי', 'אדום'],
        includeKeywords: ['פינק', 'ליידי'],
        excludeKeywords: ['גרני', 'סמית'],
      },
    ],
  },
  {
    name: 'בננות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['בננה', 'בננות'],
    includeKeywords: ['בננה', 'בננות'],
    excludeKeywords: ['מיובשת', 'צ\'יפס', 'מיץ'],
    priority: 75,
    aliases: ['בננה'],
  },
  {
    name: 'תפוזים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['תפוז', 'תפוזים'],
    includeKeywords: ['תפוז'],
    excludeKeywords: ['מיץ', 'סירופ', 'ממתק'],
    priority: 65,
    aliases: ['תפוז'],
  },
  {
    name: 'קלמנטינות',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['קלמנטינה', 'קלמנטינות', 'מנדרינה'],
    includeKeywords: ['קלמנטינ'],
    excludeKeywords: ['מיץ'],
    priority: 50,
    aliases: ['מנדרינה', 'קלמנטינה'],
  },
  {
    name: 'ענבים',
    department: 'מזון',
    category: 'פירות וירקות',
    selectionMode: 'canonical',
    keywords: ['ענבים', 'ענב'],
    includeKeywords: ['ענבים'],
    excludeKeywords: ['יין', 'מיץ', 'צימוקים'],
    priority: 50,
    aliases: ['ענב'],
  },

  // ─── דגנים, פסטה וקטניות ──────────────────────────────────────────
  {
    name: 'אורז',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['אורז', 'לבן', 'בסמטי'],
    includeKeywords: ['אורז'],
    excludeKeywords: ['עוגיות', 'חטיף', 'פריכיות'],
    priority: 80,
    aliases: [],
    variants: [
      {
        name: 'לבן',
        keywords: ['לבן', 'רגיל'],
        includeKeywords: ['לבן'],
        excludeKeywords: ['בסמטי', 'מלא', 'חום', 'סושי'],
      },
      {
        name: 'בסמטי',
        keywords: ['בסמטי'],
        includeKeywords: ['בסמטי'],
        excludeKeywords: ['לבן', 'מלא'],
      },
      {
        name: 'מלא',
        keywords: ['מלא', 'חום'],
        includeKeywords: ['מלא'],
        excludeKeywords: ['לבן', 'בסמטי'],
      },
    ],
  },
  {
    name: 'פסטה',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['פסטה', 'ספגטי', 'פנה', 'מקרוני'],
    includeKeywords: ['פסטה'],
    excludeKeywords: ['רוטב', 'מוכנה'],
    priority: 75,
    aliases: ['ספגטי', 'מקרוני', 'פנה'],
    variants: [
      {
        name: 'ספגטי',
        keywords: ['ספגטי'],
        includeKeywords: ['ספגטי'],
        excludeKeywords: ['פנה', 'מקרוני'],
      },
      {
        name: 'פנה',
        keywords: ['פנה'],
        includeKeywords: ['פנה'],
        excludeKeywords: ['ספגטי', 'מקרוני'],
      },
      {
        name: 'מקרוני',
        keywords: ['מקרוני'],
        includeKeywords: ['מקרוני'],
        excludeKeywords: ['ספגטי', 'פנה'],
      },
    ],
  },
  {
    name: 'קוסקוס',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['קוסקוס', 'פתיתים'],
    includeKeywords: ['קוסקוס'],
    excludeKeywords: ['מוכן', 'סלט'],
    priority: 55,
    aliases: ['פתיתים'],
  },
  {
    name: 'עדשים',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['עדשים', 'אדומות', 'ירוקות'],
    includeKeywords: ['עדשים'],
    excludeKeywords: ['מרק', 'שימורים'],
    priority: 45,
    aliases: [],
  },
  {
    name: 'חומוס (גרגירים)',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'canonical',
    keywords: ['חומוס', 'גרגירי', 'שימורים'],
    includeKeywords: ['חומוס'],
    excludeKeywords: ['ממרח', 'מוכן', 'סלט'],
    priority: 40,
    aliases: ['גרגירי חומוס'],
  },

  // ─── שימורים, ממרחים ורטבים ────────────────────────────────────────
  {
    name: 'טונה בשמן',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טונה', 'שמן', 'שימורים', 'פחית'],
    includeKeywords: ['טונה'],
    excludeKeywords: ['במים', 'סטייק', 'סשימי'],
    priority: 80,
    aliases: ['טונה', 'טונה בשמן'],
  },
  {
    name: 'טונה במים',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טונה', 'מים', 'שימורים', 'פחית'],
    includeKeywords: ['טונה'],
    excludeKeywords: ['בשמן', 'סטייק', 'סשימי'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'תירס מתוק',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['תירס', 'מתוק', 'שימורים', 'פחית'],
    includeKeywords: ['תירס'],
    excludeKeywords: ['קפוא', 'פופקורן', 'טורטיה'],
    priority: 60,
    aliases: ['תירס'],
  },
  {
    name: 'רסק עגבניות',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['רסק', 'עגבניות', 'עגבניה', 'משחה'],
    includeKeywords: ['רסק', 'עגבני'],
    excludeKeywords: ['קטשופ', 'רוטב'],
    priority: 65,
    aliases: ['רסק'],
  },
  {
    name: 'חומוס (ממרח)',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['חומוס', 'ממרח', 'מוכן'],
    includeKeywords: ['חומוס'],
    excludeKeywords: ['גרגירי', 'קטניות', 'יבש'],
    priority: 70,
    aliases: ['חומוס'],
  },
  {
    name: 'טחינה',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['טחינה', 'טחינה גולמית', 'שומשום'],
    includeKeywords: ['טחינה'],
    excludeKeywords: ['חלווה', 'ממתק'],
    priority: 65,
    aliases: [],
  },
  {
    name: 'קטשופ',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['קטשופ', 'עגבניות', 'רוטב'],
    includeKeywords: ['קטשופ'],
    excludeKeywords: ['רסק', 'מיונז'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'מיונז',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['מיונז', 'מיונז'],
    includeKeywords: ['מיונז'],
    excludeKeywords: ['קטשופ', 'חרדל'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'רוטב סויה',
    department: 'מזון',
    category: 'שימורים, ממרחים ורטבים',
    selectionMode: 'sku',
    keywords: ['רוטב', 'סויה'],
    includeKeywords: ['סויה', 'רוטב'],
    excludeKeywords: ['שמן', 'חלב', 'אדממה'],
    priority: 35,
    aliases: [],
  },

  // ─── שמנים, תבלינים ומוצרי אפייה ─────────────────────────────────
  {
    name: 'שמן זית',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['שמן', 'זית', 'כתית', 'מעולה'],
    includeKeywords: ['שמן', 'זית'],
    excludeKeywords: ['קנולה', 'חמניות', 'סויה', 'ספריי'],
    priority: 80,
    aliases: ['שמן זית', 'שמן'],
  },
  {
    name: 'שמן קנולה',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['שמן', 'קנולה'],
    includeKeywords: ['שמן', 'קנולה'],
    excludeKeywords: ['זית', 'חמניות'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'מלח',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'canonical',
    keywords: ['מלח', 'שולחן'],
    includeKeywords: ['מלח'],
    excludeKeywords: ['מלפפון', 'ממרח', 'מלוח'],
    priority: 60,
    aliases: [],
  },
  {
    name: 'סוכר',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'canonical',
    keywords: ['סוכר', 'לבן', 'דק'],
    includeKeywords: ['סוכר'],
    excludeKeywords: ['סוכריה', 'ממתק', 'דיאט', 'סטיוויה', 'חום'],
    priority: 70,
    aliases: ['סוכר לבן'],
  },
  {
    name: 'קמח לבן',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'canonical',
    keywords: ['קמח', 'לבן', 'רגיל', 'תכליתי'],
    includeKeywords: ['קמח'],
    excludeKeywords: ['מלא', 'כוסמין', 'שיבולת', 'תירס', 'שיפון', 'שקדים', 'תופח'],
    priority: 65,
    aliases: ['קמח'],
  },
  {
    name: 'אבקת אפייה',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'canonical',
    keywords: ['אבקת', 'אפייה'],
    includeKeywords: ['אבקת', 'אפייה'],
    excludeKeywords: ['חלבון', 'שתייה'],
    priority: 35,
    aliases: [],
  },

  // ─── חטיפים, מתוקים ושוקולד ───────────────────────────────────────
  {
    name: 'שוקולד',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['שוקולד', 'מריר', 'לבן', 'חפיסה', 'טבלה'],
    includeKeywords: ['שוקולד'],
    excludeKeywords: ['אבקה', 'שתייה', 'גלידה'],
    priority: 60,
    aliases: [],
  },
  {
    name: 'במבה',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['במבה', 'אוסם', 'בוטנים', 'חטיף'],
    includeKeywords: ['במבה'],
    excludeKeywords: [],
    priority: 65,
    aliases: [],
  },
  {
    name: 'ביסלי',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['ביסלי', 'אוסם', 'גריל', 'פיצה', 'חטיף'],
    includeKeywords: ['ביסלי'],
    excludeKeywords: [],
    priority: 65,
    aliases: [],
  },
  {
    name: 'חטיף אנרגיה',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['חטיף', 'אנרגיה', 'גרנולה', 'בר'],
    includeKeywords: ['חטיף'],
    excludeKeywords: ['במבה', 'ביסלי', 'צ\'יפס'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'צ\'יפס',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['צ\'יפס', 'תפוצ\'יפס', 'פרינגלס', 'מלוח'],
    includeKeywords: ['צ\'יפס', 'תפוצ\'יפס'],
    excludeKeywords: ['במבה', 'ביסלי'],
    priority: 55,
    aliases: ['תפוציפס'],
  },
  {
    name: 'עוגיות',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['עוגיות', 'עוגיה', 'ביסקוויט'],
    includeKeywords: ['עוגיות', 'עוגיה'],
    excludeKeywords: ['קמח', 'אבקה', 'תבנית'],
    priority: 45,
    aliases: ['ביסקוויט'],
  },
  {
    name: 'וופלים',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['וופל', 'וופלים'],
    includeKeywords: ['וופל'],
    excludeKeywords: ['מכונה', 'תבנית'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'עוגה ארוזה',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['עוגה', 'עוגת', 'שיש', 'ארוזה', 'פרוסה', 'אריזה'],
    includeKeywords: ['עוגה', 'עוגת'],
    excludeKeywords: ['עוגיות', 'קמח', 'תבנית', 'אבקה', 'תערובת', 'טרי'],
    priority: 30,
    aliases: [],
  },
  {
    name: 'פופקורן',
    department: 'מזון',
    category: 'חטיפים, מתוקים ושוקולד',
    selectionMode: 'sku',
    keywords: ['פופקורן', 'תירס', 'מלוח', 'חמאה'],
    includeKeywords: ['פופקורן'],
    excludeKeywords: ['תירס מתוק'],
    priority: 35,
    aliases: [],
  },

  // ─── דגני בוקר וארוחת בוקר ─────────────────────────────────────────
  {
    name: 'קורנפלקס',
    department: 'מזון',
    category: 'דגני בוקר וארוחת בוקר',
    selectionMode: 'sku',
    keywords: ['קורנפלקס', 'דגני', 'בוקר', 'כוכביות'],
    includeKeywords: ['קורנפלקס', 'דגני בוקר'],
    excludeKeywords: [],
    priority: 70,
    aliases: ['דגני בוקר', 'כוכביות'],
  },
  {
    name: 'גרנולה',
    department: 'מזון',
    category: 'דגני בוקר וארוחת בוקר',
    selectionMode: 'sku',
    keywords: ['גרנולה', 'שיבולת', 'שועל', 'דגני', 'בוקר'],
    includeKeywords: ['גרנולה'],
    excludeKeywords: ['חטיף'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'שיבולת שועל',
    department: 'מזון',
    category: 'דגני בוקר וארוחת בוקר',
    selectionMode: 'sku',
    keywords: ['שיבולת', 'שועל', 'אוטמיל', 'דייסה', 'דגני', 'בוקר'],
    includeKeywords: ['שיבולת', 'שועל'],
    excludeKeywords: ['גרנולה', 'חטיף', 'עוגיות', 'סנסיטיב'],
    priority: 60,
    aliases: ['אוטמיל', 'דייסה', 'שיבולת שועל'],
  },

  // ─── משקאות ────────────────────────────────────────────────────────
  {
    name: 'מים מינרליים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['מים', 'מינרליים', 'בקבוק'],
    includeKeywords: ['מים', 'מינרליים'],
    excludeKeywords: ['סודה', 'בטעם', 'מוגז'],
    priority: 75,
    aliases: ['מים'],
    variants: [
      {
        name: '1.5 ליטר',
        keywords: ['1.5', 'ליטר'],
        includeKeywords: ['1.5'],
        excludeKeywords: ['6', 'שישיה'],
      },
      {
        name: '6 חבילה',
        keywords: ['6', 'חבילה', 'שישיה'],
        includeKeywords: ['6'],
        excludeKeywords: [],
      },
    ],
  },
  {
    name: 'קולה',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['קולה', 'קוקה', 'פפסי', 'דיאט', 'זירו'],
    includeKeywords: ['קולה'],
    excludeKeywords: [],
    priority: 65,
    aliases: ['קוקה קולה', 'פפסי'],
  },
  {
    name: 'מיץ תפוזים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'sku',
    keywords: ['מיץ', 'תפוזים', 'סחוט', 'טבעי'],
    includeKeywords: ['מיץ', 'תפוז'],
    excludeKeywords: ['ענבים', 'תפוחים', 'גזר'],
    priority: 65,
    aliases: ['מיץ'],
  },
  {
    name: 'סודה / מים מוגזים',
    department: 'משקאות',
    category: 'משקאות',
    selectionMode: 'canonical',
    keywords: ['סודה', 'מוגז', 'מים מוגזים'],
    includeKeywords: ['סודה', 'מוגז'],
    excludeKeywords: ['קולה', 'בטעם'],
    priority: 45,
    aliases: ['סודה', 'מים מוגזים'],
  },

  // ─── קפואים ───────────────────────────────────────────────────────
  {
    name: 'שעועית ירוקה קפואה',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'canonical',
    keywords: ['שעועית', 'ירוקה', 'קפואה', 'קפוא'],
    includeKeywords: ['שעועית', 'קפוא'],
    excludeKeywords: ['שימורים', 'יבשה'],
    priority: 40,
    aliases: ['שעועית קפואה'],
  },
  {
    name: 'אפונה קפואה',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'canonical',
    keywords: ['אפונה', 'קפואה', 'קפוא'],
    includeKeywords: ['אפונה', 'קפוא'],
    excludeKeywords: ['שימורים', 'יבשה'],
    priority: 40,
    aliases: ['אפונה קפואה'],
  },
  {
    name: 'צ\'יפס קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['צ\'יפס', 'קפוא', 'תפוחי אדמה'],
    includeKeywords: ['צ\'יפס', 'קפוא'],
    excludeKeywords: ['חטיף'],
    priority: 45,
    aliases: [],
  },

  {
    name: 'פילה סלמון קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['פילה', 'סלמון', 'קפוא', 'דג'],
    includeKeywords: ['סלמון', 'קפוא'],
    excludeKeywords: ['טרי', 'מעושן', 'סושי'],
    priority: 55,
    aliases: ['סלמון קפוא'],
  },
  {
    name: 'פילה אמנון קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['פילה', 'אמנון', 'קפוא', 'דג', 'טילאפיה'],
    includeKeywords: ['אמנון', 'קפוא'],
    excludeKeywords: ['טרי', 'סלמון'],
    priority: 45,
    aliases: ['טילאפיה קפוא'],
  },
  {
    name: 'דג מצופה קפוא',
    department: 'מזון',
    category: 'קפואים',
    selectionMode: 'sku',
    keywords: ['דג', 'מצופה', 'קפוא', 'פירורים', 'שניצל דג'],
    includeKeywords: ['דג', 'קפוא'],
    excludeKeywords: ['פילה', 'סלמון', 'אמנון', 'טרי'],
    priority: 40,
    aliases: ['שניצל דג'],
  },

  // ─── קפה ותה ──────────────────────────────────────────────────────
  {
    name: 'קפה טורקי',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['קפה', 'טורקי', 'עלית', 'נמס'],
    includeKeywords: ['קפה', 'טורקי'],
    excludeKeywords: ['נמס', 'קפסולות', 'אספרסו'],
    priority: 75,
    aliases: ['קפה', 'קפה שחור'],
  },
  {
    name: 'קפה נמס',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['קפה', 'נמס', 'טסטרס', 'נסקפה'],
    includeKeywords: ['קפה', 'נמס'],
    excludeKeywords: ['טורקי', 'קפסולות'],
    priority: 60,
    aliases: ['נסקפה'],
  },
  {
    name: 'תה',
    department: 'מזון',
    category: 'קפה ותה',
    selectionMode: 'sku',
    keywords: ['תה', 'שקיקים', 'נענע', 'ירוק', 'שחור'],
    includeKeywords: ['תה'],
    excludeKeywords: ['קפה'],
    priority: 60,
    aliases: [],
  },

  // ─── אגוזים וגרעינים ────────────────────────────────────────────────
  {
    name: 'קשיו',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['קשיו', 'קשיוז', 'אגוזי קשיו', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['קשיו'],
    excludeKeywords: ['חמאה', 'ממרח', 'תפזורת', 'משקל'],
    priority: 45,
    aliases: [],
  },
  {
    name: 'שקדים',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['שקדים', 'שקד', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['שקדים'],
    excludeKeywords: ['חלב', 'משקה', 'חמאה', 'ממרח', 'תפזורת', 'משקל'],
    priority: 45,
    aliases: [],
  },
  {
    name: 'אגוזי מלך',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['אגוזי מלך', 'אגוז מלך', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['אגוז', 'מלך'],
    excludeKeywords: ['חמאה', 'ממרח', 'תפזורת', 'משקל'],
    priority: 40,
    aliases: [],
  },
  {
    name: 'גרעיני חמניה',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['גרעיני חמניה', 'גרעינים', 'חמניות', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['גרעינ', 'חמני'],
    excludeKeywords: ['שמן', 'תפזורת', 'משקל'],
    priority: 40,
    aliases: ['גרעינים'],
  },
  {
    name: 'פיסטוק',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['פיסטוק', 'פיסטוקים', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['פיסטוק'],
    excludeKeywords: ['גלידה', 'תפזורת', 'משקל'],
    priority: 35,
    aliases: [],
  },
  {
    name: 'בוטנים',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'sku',
    keywords: ['בוטנים', 'בוטן', 'פיצוחים', 'ארוז', 'שקית'],
    includeKeywords: ['בוטנים'],
    excludeKeywords: ['חמאה', 'ממרח', 'במבה', 'תפזורת', 'משקל'],
    priority: 40,
    aliases: [],
  },
  {
    name: 'פיצוחים תפזורת',
    department: 'מזון',
    category: 'אגוזים וגרעינים',
    selectionMode: 'canonical',
    keywords: ['פיצוחים', 'אגוזים', 'גרעינים', 'שקדים', 'קשיו', 'בוטנים', 'פיסטוק', 'אגוזי מלך', 'תפזורת', 'משקל'],
    includeKeywords: ['פיצוחים', 'תפזורת', 'אגוז', 'גרעינ', 'משקל'],
    excludeKeywords: ['ארוז', 'שקית', 'חמאה', 'ממרח'],
    priority: 25,
    aliases: [],
  },

  // ─── ניקיון ובית ──────────────────────────────────────────────────
  {
    name: 'נייר טואלט',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['נייר', 'טואלט', 'גלילים'],
    includeKeywords: ['נייר', 'טואלט'],
    excludeKeywords: ['מגבת', 'סופג'],
    priority: 70,
    aliases: ['נייר טואלט'],
  },
  {
    name: 'סבון כלים',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'sku',
    keywords: ['סבון', 'כלים', 'נוזלי'],
    includeKeywords: ['סבון', 'כלים'],
    excludeKeywords: ['גוף', 'ידיים', 'כביסה'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'אקונומיקה',
    department: 'ניקיון ובית',
    category: 'ניקיון ובית',
    selectionMode: 'canonical',
    keywords: ['אקונומיקה', 'לבן', 'חומר חיטוי'],
    includeKeywords: ['אקונומיקה'],
    excludeKeywords: [],
    priority: 45,
    aliases: [],
  },
  // ─── משקאות צמחיים ──────────────────────────────────────────────
  {
    name: 'משקה שיבולת שועל',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['משקה', 'שיבולת', 'שועל', 'אוטלי', 'צמחי'],
    includeKeywords: ['שיבולת', 'שועל'],
    excludeKeywords: ['דייסה', 'גרנולה', 'חטיף', 'עוגיות'],
    priority: 55,
    aliases: ['חלב שיבולת שועל'],
  },
  {
    name: 'משקה שקדים',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['משקה', 'שקדים', 'שקד', 'צמחי', 'אלפרו'],
    includeKeywords: ['שקד'],
    excludeKeywords: ['פיצוחים', 'ארוז', 'שקית', 'גלידה', 'חטיף'],
    priority: 55,
    aliases: ['חלב שקדים'],
  },
  {
    name: 'משקה סויה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['משקה', 'סויה', 'סוי', 'צמחי', 'אלפרו'],
    includeKeywords: ['סויה'],
    excludeKeywords: ['רוטב', 'אדממה', 'טופו', 'שעועית'],
    priority: 55,
    aliases: ['חלב סויה'],
  },
  // ─── גבינות נוספות ──────────────────────────────────────────────
  {
    name: 'גבינה בולגרית',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'בולגרית', 'מלוחה'],
    includeKeywords: ['בולגרית'],
    excludeKeywords: [],
    priority: 60,
    aliases: [],
  },
  {
    name: 'גבינת עיזים',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['גבינה', 'עיזים', 'עז'],
    includeKeywords: ['עיזים'],
    excludeKeywords: ['יוגורט', 'חלב'],
    priority: 55,
    aliases: ['גבינה עז'],
  },
  {
    name: 'פרמזן',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['פרמזן', 'פרמג\'נו', 'גבינה', 'איטלקית', 'מגורדת'],
    includeKeywords: ['פרמזן'],
    excludeKeywords: [],
    priority: 55,
    aliases: ['פרמג\'נו'],
  },
  {
    name: 'ריקוטה',
    department: 'מזון',
    category: 'חלב ומוצרי חלב',
    selectionMode: 'sku',
    keywords: ['ריקוטה', 'גבינה', 'איטלקית'],
    includeKeywords: ['ריקוטה'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
  // ─── עוף ───────────────────────────────────────────────────────
  {
    name: 'עוף שלם',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['עוף', 'שלם', 'פרגית', 'קפוא', 'טרי'],
    includeKeywords: ['עוף', 'שלם'],
    excludeKeywords: ['חזה', 'כנף', 'כרע', 'שוק', 'שניצל', 'נקניק'],
    priority: 60,
    aliases: ['פרגית'],
  },
  {
    name: 'כנפיים עוף',
    department: 'מזון',
    category: 'בשר ועוף',
    selectionMode: 'sku',
    keywords: ['כנפיים', 'כנף', 'עוף', 'טרי'],
    includeKeywords: ['כנפיי'],
    excludeKeywords: ['שניצל', 'נקניק'],
    priority: 55,
    aliases: ['כנף עוף'],
  },
  // ─── דגים ──────────────────────────────────────────────────────
  {
    name: 'דג טרי',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['דג', 'דגים', 'טרי', 'פילה'],
    includeKeywords: ['דג'],
    excludeKeywords: ['קפוא', 'שימורים', 'פחית', 'מצופה', 'מעושן', 'מלוח', 'דגני'],
    priority: 75,
    aliases: ['דגים'],
  },
  {
    name: 'סלמון טרי',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['סלמון', 'טרי', 'פילה', 'נורבגי'],
    includeKeywords: ['סלמון'],
    excludeKeywords: ['קפוא', 'מעושן', 'מלוח', 'שימורים'],
    priority: 60,
    aliases: [],
  },
  {
    name: 'דניס',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['דניס', 'דג', 'טרי'],
    includeKeywords: ['דניס'],
    excludeKeywords: ['קפוא'],
    priority: 55,
    aliases: [],
  },
  {
    name: 'ברמונדי',
    department: 'מזון',
    category: 'דגים ופירות ים',
    selectionMode: 'sku',
    keywords: ['ברמונדי', 'דג', 'טרי', 'פילה'],
    includeKeywords: ['ברמונדי'],
    excludeKeywords: ['קפוא'],
    priority: 55,
    aliases: [],
  },
  // ─── לחם ומאפים נוספים ─────────────────────────────────────────
  {
    name: 'באגט',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'canonical',
    keywords: ['באגט', 'בגט', 'צרפתי'],
    includeKeywords: ['באגט'],
    excludeKeywords: [],
    priority: 50,
    aliases: ['בגט'],
  },
  {
    name: 'לחם שיפון',
    department: 'מזון',
    category: 'לחם ומאפים',
    selectionMode: 'sku',
    keywords: ['לחם', 'שיפון', 'כהה'],
    includeKeywords: ['שיפון'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
  // ─── פסטה / אטריות ────────────────────────────────────────────
  {
    name: 'אטריות',
    department: 'מזון',
    category: 'פסטה, אורז וקטניות',
    selectionMode: 'sku',
    keywords: ['אטריות', 'אטריה', 'נודלס', 'רחבות', 'ביצים'],
    includeKeywords: ['אטריו'],
    excludeKeywords: ['אורז'],
    priority: 50,
    aliases: ['נודלס'],
  },
  // ─── קמח ──────────────────────────────────────────────────────
  {
    name: 'קמח מלא',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'מלא', 'חיטה'],
    includeKeywords: ['קמח', 'מלא'],
    excludeKeywords: [],
    priority: 76,
    aliases: ['קמח חיטה מלא'],
  },
  {
    name: 'קמח כוסמין',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'כוסמין', 'ספלט'],
    includeKeywords: ['קמח', 'כוסמין'],
    excludeKeywords: [],
    priority: 50,
    aliases: ['קמח ספלט'],
  },
  {
    name: 'קמח שיפון',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'שיפון'],
    includeKeywords: ['קמח', 'שיפון'],
    excludeKeywords: ['לחם'],
    priority: 50,
    aliases: [],
  },
  {
    name: 'קמח שקדים',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'sku',
    keywords: ['קמח', 'שקדים'],
    includeKeywords: ['קמח', 'שקדים'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
  {
    name: 'קמח תופח',
    department: 'מזון',
    category: 'שמנים, תבלינים ואפייה',
    selectionMode: 'canonical',
    keywords: ['קמח', 'תופח'],
    includeKeywords: ['קמח', 'תופח'],
    excludeKeywords: [],
    priority: 50,
    aliases: [],
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  await connectMongo();

  const groupRepo = new ProductGroupRepository();
  const variantRepo = new ProductVariantRepository();

  let groupCount = 0;
  let variantCount = 0;

  for (const seed of SEED_GROUPS) {
    const normalizedName = normalizeName(seed.name);
    const normalizedKeywords = seed.keywords.map(normalizeName).filter(Boolean);

    const group = await groupRepo.upsertByName({
      name: seed.name,
      normalizedName,
      department: seed.department,
      category: seed.category,
      selectionMode: seed.selectionMode,
      keywords: seed.keywords,
      normalizedKeywords,
      includeKeywords: seed.includeKeywords,
      excludeKeywords: seed.excludeKeywords,
      priority: seed.priority,
      aliases: seed.aliases,
    });
    groupCount++;

    if (seed.variants) {
      for (const v of seed.variants) {
        const normalizedVarKeywords = v.keywords.map(normalizeName).filter(Boolean);

        await variantRepo.upsertByGroupAndName({
          groupId: group.id,
          name: v.name,
          keywords: v.keywords,
          normalizedKeywords: normalizedVarKeywords,
          includeKeywords: v.includeKeywords ?? [],
          excludeKeywords: v.excludeKeywords ?? [],
        });
        variantCount++;
      }
    }
  }

  // Clean up stale groups that no longer exist in the seed
  const seededNames = new Set(SEED_GROUPS.map((s) => normalizeName(s.name)));
  const ProductGroupModel = mongoose.connection.collection('productgroups');
  const allDocs = await ProductGroupModel.find({}, { projection: { normalizedName: 1 } }).toArray();
  const staleIds = allDocs
    .filter((d) => !seededNames.has(d.normalizedName))
    .map((d) => d._id);
  if (staleIds.length > 0) {
    await ProductGroupModel.deleteMany({ _id: { $in: staleIds } });
    console.log(`Removed ${staleIds.length} stale product groups.`);
  }

  console.log(`Seeded ${groupCount} product groups and ${variantCount} variants.`);

  await mongoose.disconnect();
  process.exit(0);
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
