import type { ChainProduct } from '../models/chain-product.model';
import type { IChainProductDocument } from '../infrastructure/db/chain-product.mongoose.model';

export const mapChainProduct = (doc: IChainProductDocument): ChainProduct => ({
  id: String(doc._id),
  chainId: doc.chainId,
  externalId: doc.externalId,
  barcode: doc.barcode,
  originalName: doc.originalName,
  normalizedName: doc.normalizedName,
  price: doc.price,
  unit: doc.unit,
  quantity: doc.quantity,
  isActive: doc.isActive,
  lastSeenAt: doc.lastSeenAt,
  promotions: (doc.promotions ?? []).map((promotion) => ({
    chainId: promotion.chainId,
    promotionId: promotion.promotionId,
    description: promotion.description,
    startAt: promotion.startAt,
    endAt: promotion.endAt,
    rewardType: promotion.rewardType,
    discountType: promotion.discountType,
    discountRate: promotion.discountRate,
    minQty: promotion.minQty,
    maxQty: promotion.maxQty,
    discountedPrice: promotion.discountedPrice,
    minItemsOffered: promotion.minItemsOffered,
    items: (promotion.items ?? []).map((item) => ({
      itemCode: item.itemCode,
      itemType: item.itemType,
      isGiftItem: item.isGiftItem,
    })),
    parsedPromotionKind: promotion.parsedPromotionKind,
    rawPayload: promotion.rawPayload ?? {},
    promotionUpdateAt: promotion.promotionUpdateAt,
    discountedPricePerMida: promotion.discountedPricePerMida,
    allowMultipleDiscounts: promotion.allowMultipleDiscounts,
    minPurchaseAmount: promotion.minPurchaseAmount,
    isWeightedPromo: promotion.isWeightedPromo,
    clubId: promotion.clubId,
    remarks: promotion.remarks,
    isGift: promotion.isGift,
    isCoupon: promotion.isCoupon,
    isTotal: promotion.isTotal,
  })),
  hasActivePromotions: doc.hasActivePromotions ?? false,
  lastPromotionSyncAt: doc.lastPromotionSyncAt,
  createdAt: doc.createdAt,
  updatedAt: doc.updatedAt,
});
