import type { ChainProduct } from '../models/chain-product.model';
import type { IChainProductDocument } from '../infrastructure/db/chain-product.mongoose.model';

export const mapChainProduct = (doc: IChainProductDocument): ChainProduct => ({
  id: String(doc._id),
  chainId: doc.chainId,
  productId: doc.productId ? String(doc.productId) : undefined,
  productType: doc.productType,
  externalId: doc.externalId,
  barcode: doc.barcode,
  originalName: doc.originalName,
  normalizedName: doc.normalizedName,
  price: doc.price,
  priceUpdateDate: doc.priceUpdateDate,
  unit: doc.unit,
  quantity: doc.quantity,
  unitType: doc.unitType,
  isActive: doc.isActive,
  lastSeenAt: doc.lastSeenAt,
  imageUrl: doc.imageUrl,
  promotions: (doc.promotions ?? []).map((promotion) => ({
    chainId: promotion.chainId,
    promotionId: promotion.promotionId,
    description: promotion.description,
    startAt: promotion.startAt,
    endAt: promotion.endAt,
    parsedPromotionKind: promotion.parsedPromotionKind,
    discountType: promotion.discountType,
    discountRate: promotion.discountRate,
    discountedPrice: promotion.discountedPrice,
    minQty: promotion.minQty,
    maxQty: promotion.maxQty,
    minItemsOffered: promotion.minItemsOffered,
    discountedPricePerMida: promotion.discountedPricePerMida,
    minPurchaseAmount: promotion.minPurchaseAmount,
    isWeightedPromo: promotion.isWeightedPromo,
    allowMultipleDiscounts: promotion.allowMultipleDiscounts,
    isGift: promotion.isGift,
    isCoupon: promotion.isCoupon,
    isTotal: promotion.isTotal,
    clubId: promotion.clubId,
    remarks: promotion.remarks,
  })),
  hasActivePromotions: doc.hasActivePromotions ?? false,
  lastPromotionSyncAt: doc.lastPromotionSyncAt,
  createdAt: doc.createdAt,
  updatedAt: doc.updatedAt,
});
