import type { Promotion } from '../models/promotion.model';
import type { IPromotionDocument } from '../infrastructure/db/promotion.mongoose.model';

export const mapPromotion = (doc: IPromotionDocument): Promotion => ({
  id: String(doc._id),
  chainId: doc.chainId,
  storeId: doc.storeId,
  promotionId: doc.promotionId,
  description: doc.description,
  startAt: doc.startAt,
  endAt: doc.endAt,
  rewardType: doc.rewardType,
  discountType: doc.discountType,
  discountRate: doc.discountRate,
  minQty: doc.minQty,
  maxQty: doc.maxQty,
  discountedPrice: doc.discountedPrice,
  minItemsOffered: doc.minItemsOffered,
  items: doc.items.map((item) => ({
    itemCode: item.itemCode,
    itemType: item.itemType,
    isGiftItem: item.isGiftItem,
  })),
  parsedPromotionKind: doc.parsedPromotionKind,
  rawPayload: doc.rawPayload,
  promotionUpdateAt: doc.promotionUpdateAt,
  discountedPricePerMida: doc.discountedPricePerMida,
  allowMultipleDiscounts: doc.allowMultipleDiscounts,
  minPurchaseAmount: doc.minPurchaseAmount,
  isWeightedPromo: doc.isWeightedPromo,
  clubId: doc.clubId,
  remarks: doc.remarks,
  isGift: doc.isGift,
  isCoupon: doc.isCoupon,
  isTotal: doc.isTotal,
  itemCodes: doc.itemCodes,
  isActive: doc.isActive,
  lastSeenAt: doc.lastSeenAt,
  createdAt: doc.createdAt,
  updatedAt: doc.updatedAt,
});
